#ifndef _SRC_STAGE_AST_ASTS_AST_LAYOUT_AST_LAYOUT_CREATE_AST_LAYOUT_CREATE_H_
#define _SRC_STAGE_AST_ASTS_AST_LAYOUT_AST_LAYOUT_CREATE_AST_LAYOUT_CREATE_H_

// base
#include <base.h>

ast_layout_t* ast_layout_create();

#endif // _SRC_STAGE_AST_ASTS_AST_LAYOUT_AST_LAYOUT_CREATE_AST_LAYOUT_CREATE_H_
