---
version: 2
updates:
  - package-ecosystem: bun
    directory: /
    open-pull-requests-limit: 2
    schedule:
      interval: weekly
    groups:
      bun-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 2
    schedule:
      interval: weekly
    groups:
      github-actions-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7
  - package-ecosystem: npm
    directory: /tests/en/apps/httpbench/bench/node
    open-pull-requests-limit: 1
    schedule:
      interval: monthly
    groups:
      httpbench-node-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 7
