---
config:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - config/**/*
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - docs/**/*
              - '**/*.md'
editor:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - editor/*
tests:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - compiler/tests/*
tests-fa:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - compiler/tests/fa/**/*
tests-ar:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - compiler/tests/ar/**/*
tests-en:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - compiler/tests/en/**/*
github:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .github/**/*
source-code:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '**/*.c'
scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '**/*.sh'
repo:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '*'
