labels:
  - name: docs
    globs:
      - "docs/**"
  - name: examples
    globs:
      - "examples/**"
  - name: github-actions
    globs:
      - ".github/**"
  - name: source-code
    globs:
      - "**/*.c"
  - name: scripts
    globs:
      - "**/*.sh"
  - name: repo
    globs:
      - "*"


