# .github/labeler.yml
# Pull Request Labeler Configuration
# Organized by category: area, lang, type, infra, tooling, deps, security, priority

# === AREA labels (where the change is) ===
area/config:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - ".github/**"
              - "config/**/*"
              - "tools/config/**"
              - "*.config"
              - ".editorconfig"

area/docs:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "docs/**"
              - "**/*.md"
              - "README*"
              - "CHANGELOG*"
              - "CONTRIBUTING*"

area/examples:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "examples/**"
              - "samples/**"

area/source:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "src/**"
              - "lib/**"
              - "core/**"

area/compiler:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "compiler/**"
              - "frontend/**"
              - "backend/**"

area/parser:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "parser/**"
              - "src/parser/**"
              - "**/parser.*"

area/interpreter:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "interpreter/**"
              - "src/interpreter/**"
              - "**/interpreter.*"

area/scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "scripts/**"
              - "ci/**"
              - "tools/**"

area/repo:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - ".gitignore"
              - ".gitattributes"
              - "LICENSE*"

# === LANGUAGE / FILETYPE labels ===
lang/c-cpp:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "**/*.c"
              - "**/*.cpp"
              - "**/*.h"
              - "**/*.hpp"
              - "Makefile"
              - "CMakeLists.txt"

lang/rust:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "**/*.rs"
              - "Cargo.toml"
              - "Cargo.lock"

lang/python:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "**/*.py"
              - "pyproject.toml"
              - "requirements.txt"
              - "setup.py"

lang/javascript:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "**/*.js"
              - "**/*.ts"
              - "**/*.jsx"
              - "**/*.tsx"
              - "package.json"
              - "tsconfig.json"

lang/go:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "**/*.go"
              - "go.mod"
              - "go.sum"

lang/shell:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "**/*.sh"
              - "**/*.bash"

# === TYPE labels (what kind of change) ===
type/bug:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "bugfix/**"
              - "fix/**"

type/feature:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "feat/**"
              - "feature/**"
              - "features/**"

type/refactor:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "refactor/**"
              - "**/*refactor*"

type/documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "docs/**"
              - "**/*.md"
              - "README*"

type/tests:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "test/**"
              - "tests/**"
              - "**/*.spec.*"
              - "**/*.test.*"
              - "**/*_test.*"

type/chore:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "chore/**"
              - ".github/**"
              - "scripts/**"

type/perf:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "perf/**"
              - "benchmarks/**"
              - "**/*benchmark*"

# === INFRASTRUCTURE labels ===
infra/ci:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - ".github/workflows/**"
              - ".github/actions/**"
              - "ci/**"
              - ".travis.yml"
              - ".circleci/**"
              - "azure-pipelines.yml"

infra/docker:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "docker/**"
              - "Dockerfile*"
              - "docker-compose*.yml"
              - ".dockerignore"

infra/build:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "Makefile"
              - "**/Makefile"
              - "CMakeLists.txt"
              - "build/**"
              - "*.cmake"

# === DEPENDENCIES & SECURITY ===
deps:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "Cargo.lock"
              - "package-lock.json"
              - "poetry.lock"
              - "requirements.txt"
              - "go.sum"
              - "Pipfile.lock"
              - "yarn.lock"

security:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "security/**"
              - "SECURITY.md"
              - ".github/dependabot.yml"
              - "dependabot.yml"

# === TOOLING ===
tooling/linter:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - ".eslintrc*"
              - ".pylintrc"
              - ".clang-format"
              - ".clang-tidy"
              - "rustfmt.toml"
              - ".rustfmt.toml"

tooling/formatter:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - ".prettierrc*"
              - ".clang-format"
              - "rustfmt.toml"

# === PRIORITY (based on critical areas) ===
priority/high:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "core/**"
              - "compiler/**"
              - "src/main.*"
              - "SECURITY.md"

priority/critical:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - "security/**"
              - "src/core/**"
