labels:
  docs:
    - "doc/**"
  examples:
    - "examples/**"
  github-actions:
   - ".github/**"
  github-actions:
   - ".github/**"
  source-code:
    - "**/*.c"
  scripts:
    - '**/*.sh'
  repo:
    - "*"
