documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - docs/**/*

examples:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - examples/**/*

github:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - .github/**/*

source-code:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '**/*.c'

scripts:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '**/*.sh'

repo:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              '*'
