# Add 'docs' label to any change to docs files
docs:
  - any: ["docs/**/*"]
# Add 'examples' label to any change to examples files
examples:
  - any: ["examples/**/*"]
# Add 'github-actions' label to any change to .github files
github-actions:
  - any: [".github/**/*"]
# Add 'source-code' label to any change to C source files
source-code:
  - any: ["**/*.c"]
# Add 'scripts' label to any change to shell script files
scripts:
  - any: ["**/*.sh"]
# Add 'repo' label to any root file changes
repo:
  - "*"
