" Vim filetype plugin - Language: Salam
" Generated by extensions/tools/gen_syntaxes.salam

if exists('b:did_ftplugin')
  finish
endif
let b:did_ftplugin = 1

let s:cpo_save = &cpo
set cpo&vim

setlocal commentstring=//\ %s
setlocal comments=s1:/*,mb:*,ex:*/,://
setlocal suffixesadd=.salam
setlocal includeexpr=substitute(v:fname,'\\.','/','g')
setlocal formatoptions-=t
setlocal formatoptions+=croqlj

setlocal expandtab
setlocal shiftwidth=4
setlocal softtabstop=4
setlocal tabstop=4

compiler salam

if exists('loaded_matchit') && !exists('b:match_words')
  let b:match_ignorecase = 0
  let b:match_words = '\<\%(پیاده‌سازی\|interface\|component\|تاهنگام\|struct\|layout\|extern\|repeat\|کارکرد\|ساختار\|چیدمان\|برگزین\|until\|match\|while\|شمارش\|خارجی\|func\|type\|enum\|impl\|each\|ریخت\|واسط\|سازه\|چرخه\|اگر\|if\|on\|بر\|هر\)\>:\<\%(وگرنه\|else\)\>:\<\%(پایان\|end\)\>'
endif

let b:undo_ftplugin = 'setlocal commentstring< comments< suffixesadd<'
      \ . ' includeexpr< formatoptions< expandtab< shiftwidth< softtabstop< tabstop<'
      \ . ' | unlet! b:match_words b:match_ignorecase'

let &cpo = s:cpo_save
unlet s:cpo_save
