#ifndef _SRC_UTILITY_UTF8_UTF8_IS_CONTINUATION_BYTE_UTF8_IS_CONTINUATION_BYTE_H_
#define _SRC_UTILITY_UTF8_UTF8_IS_CONTINUATION_BYTE_UTF8_IS_CONTINUATION_BYTE_H_

#include <stdbool.h> // for bool

// base
#include <base.h>

bool utf8_is_continuation_byte(char c);

#endif // _SRC_UTILITY_UTF8_UTF8_IS_CONTINUATION_BYTE_UTF8_IS_CONTINUATION_BYTE_H_
