---
# https://prek.j178.dev/installation/
default_stages: [pre-commit, pre-push]
default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3
minimum_prek_version: '0.3.4'
repos:
  - repo: meta
    hooks:
      - id: identity
        name: run identity check
        description: check you have set your git identity
        priority: 10
      - id: check-hooks-apply
        name: run check hooks apply
        description: check that all the hooks apply to the repository
        priority: 10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-illegal-windows-names
        name: run check-illegal-windows-names
        description: check for Windows-illegal file names
        priority: 50
  - repo: https://github.com/gitleaks/gitleaks
    rev: 83d9cd684c87d95d656c1458ef04895a7f1cbd8e # frozen: v8.30.1
    hooks:
      - id: gitleaks
        name: run gitleaks
        description: check for secrets with gitleaks
        priority: 50
