CC = gcc
EMCC = emcc
CFLAGS_DEV = -g -fsanitize=undefined,address -Wall -lefence
CFLAGS_PROD = -O3
INPUT_FILE = salam.c
OUTPUT_FILE = s
WEB_OUTPUT = salam.js
EXAMPLE_FILE = examples/input.salam

.PHONY: all clean dev prod web

all: dev

dev: CFLAGS=$(CFLAGS_DEV)
dev: $(OUTPUT_FILE)

prod: CFLAGS=$(CFLAGS_PROD)
prod: $(OUTPUT_FILE)

$(OUTPUT_FILE): $(INPUT_FILE)
	$(CC) $(CFLAGS) -o $(OUTPUT_FILE) $(INPUT_FILE)

web: $(INPUT_FILE)
	$(EMCC) $(INPUT_FILE) -o $(WEB_OUTPUT) -s ALLOW_MEMORY_GROWTH=1 -s EXIT_RUNTIME=1 -s NO_EXIT_RUNTIME=1

clean:
	rm -f $(OUTPUT_FILE) $(WEB_OUTPUT)
