/* AUTO-GENERATED by tools/salam/gen-examples.salam from examples/{en,fa}/editor-selected/.
   Do not edit by hand: edit the .salam sources, then re-run the generator. */
window.SALAM_EXAMPLES = [
  {
    "id": "hello", "mode": "app", "title": { "en": "Hello", "fa": "سلام" },
    "code": {
      "en": "func main:\n    name str = \"Salam\"\n    println \"Hello,\", name\n    println \"2 + 3 =\", 2 + 3\nend\n",
      "fa": "تابع اصلی:\n    نام رشته = \"سلام\"\n    چاپ \"سلام،\", نام\n    چاپ \"۲ + ۳ =\", 2 + 3\nپایان\n"
    }
  },
  {
    "id": "fizzbuzz", "mode": "app", "title": { "en": "FizzBuzz", "fa": "فیزباز" },
    "code": {
      "en": "func main:\n    for mut i = 1; i <= 15; i = i + 1:\n        if i % 15 == 0: println \"FizzBuzz\"\n        else if i % 3 == 0: println \"Fizz\"\n        else if i % 5 == 0: println \"Buzz\"\n        else:\n            println i\n        end\n    end\nend\n",
      "fa": "تابع اصلی:\n    برای متغیر i = 1; i <= 15; i = i + 1:\n        اگر i % 15 == 0: چاپ \"فیزباز\"\n        وگرنه اگر i % 3 == 0: چاپ \"فیز\"\n        وگرنه اگر i % 5 == 0: چاپ \"باز\"\n        وگرنه:\n            چاپ i\n        پایان\n    پایان\nپایان\n"
    }
  },
  {
    "id": "factorial", "mode": "app", "title": { "en": "Factorial", "fa": "فاکتوریل" },
    "code": {
      "en": "func fact(n i32) i32:\n    if n <= 1: ret 1 end\n    ret n * fact(n - 1)\nend\nfunc main:\n    for mut i = 1; i <= 6; i = i + 1:\n        println i, \"! =\", fact(i)\n    end\nend\n",
      "fa": "تابع فاکتوریل(ن صحیح۳۲) صحیح۳۲:\n    اگر ن <= 1: بازگشت 1 پایان\n    بازگشت ن * فاکتوریل(ن - 1)\nپایان\nتابع اصلی:\n    برای متغیر i = 1; i <= 6; i = i + 1:\n        چاپ i, \"! =\", فاکتوریل(i)\n    پایان\nپایان\n"
    }
  },
  {
    "id": "fibonacci", "mode": "app", "title": { "en": "Fibonacci", "fa": "فیبوناچی" },
    "code": {
      "en": "func fib(n i32) i32:\n    if n < 2: ret n end\n    ret fib(n - 1) + fib(n - 2)\nend\nfunc main:\n    mut line str = \"\"\n    for mut i = 0; i < 12; i = i + 1: line = line + fib(i) + \" \" end\n    println \"Fibonacci:\", line\nend\n",
      "fa": "تابع فیب(ن صحیح۳۲) صحیح۳۲:\n    اگر ن < 2: بازگشت ن پایان\n    بازگشت فیب(ن - 1) + فیب(ن - 2)\nپایان\nتابع اصلی:\n    متغیر خط رشته = \"\"\n    برای متغیر i = 0; i < 12; i = i + 1: خط = خط + فیب(i) + \" \" پایان\n    چاپ \"فیبوناچی:\", خط\nپایان\n"
    }
  },
  {
    "id": "primes", "mode": "app", "title": { "en": "Primes", "fa": "اعداد اول" },
    "code": {
      "en": "func is_prime(n i32) bool:\n    if n < 2: ret false end\n    for mut i = 2; i * i <= n; i = i + 1:\n        if n % i == 0: ret false end\n    end\n    ret true\nend\nfunc main:\n    mut line str = \"\"\n    for mut n = 2; n <= 30; n = n + 1:\n        if is_prime(n): line = line + n + \" \" end\n    end\n    println \"Primes up to 30:\", line\nend\n",
      "fa": "تابع اول_است(ن صحیح۳۲) منطقی:\n    اگر ن < 2: بازگشت نادرست پایان\n    برای متغیر i = 2; i * i <= ن; i = i + 1:\n        اگر ن % i == 0: بازگشت نادرست پایان\n    پایان\n    بازگشت درست\nپایان\nتابع اصلی:\n    متغیر خط رشته = \"\"\n    برای متغیر ن = 2; ن <= 30; ن = ن + 1:\n        اگر اول_است(ن): خط = خط + ن + \" \" پایان\n    پایان\n    چاپ \"اعداد اول تا ۳۰:\", خط\nپایان\n"
    }
  },
  {
    "id": "gcd", "mode": "app", "title": { "en": "GCD", "fa": "ب.م.م" },
    "code": {
      "en": "func gcd(a i32, b i32) i32:\n    mut x i32 = a\n    mut y i32 = b\n    while y != 0:\n        mut t i32 = y\n        y = x % y\n        x = t\n    end\n    ret x\nend\nfunc main:\n    println \"gcd(48, 36) =\", gcd(48, 36)\n    println \"gcd(17, 5) =\", gcd(17, 5)\nend\n",
      "fa": "تابع بمم(الف صحیح۳۲, ب صحیح۳۲) صحیح۳۲:\n    متغیر ایکس صحیح۳۲ = الف\n    متغیر ایگرگ صحیح۳۲ = ب\n    تاوقتی ایگرگ != 0:\n        متغیر ت صحیح۳۲ = ایگرگ\n        ایگرگ = ایکس % ایگرگ\n        ایکس = ت\n    پایان\n    بازگشت ایکس\nپایان\nتابع اصلی:\n    چاپ \"ب.م.م ۴۸ و ۳۶ =\", بمم(48, 36)\n    چاپ \"ب.م.م ۱۷ و ۵ =\", بمم(17, 5)\nپایان\n"
    }
  },
  {
    "id": "bubblesort", "mode": "app", "title": { "en": "Bubble sort", "fa": "مرتب‌سازی حبابی" },
    "code": {
      "en": "func main:\n    mut a i32[6] = [5, 2, 8, 1, 9, 3]\n    for mut i = 0; i < 6; i = i + 1:\n        for mut j = 0; j < 5 - i; j = j + 1:\n            if a[j] > a[j + 1]:\n                mut t i32 = a[j]\n                a[j] = a[j + 1]\n                a[j + 1] = t\n            end\n        end\n    end\n    mut line str = \"\"\n    for mut k = 0; k < 6; k = k + 1: line = line + a[k] + \" \" end\n    println \"Sorted:\", line\nend\n",
      "fa": "تابع اصلی:\n    متغیر آ صحیح۳۲[6] = [5, 2, 8, 1, 9, 3]\n    برای متغیر i = 0; i < 6; i = i + 1:\n        برای متغیر ج = 0; ج < 5 - i; ج = ج + 1:\n            اگر آ[ج] > آ[ج + 1]:\n                متغیر ت صحیح۳۲ = آ[ج]\n                آ[ج] = آ[ج + 1]\n                آ[ج + 1] = ت\n            پایان\n        پایان\n    پایان\n    متغیر خط رشته = \"\"\n    برای متغیر ک = 0; ک < 6; ک = ک + 1: خط = خط + آ[ک] + \" \" پایان\n    چاپ \"مرتب‌شده:\", خط\nپایان\n"
    }
  },
  {
    "id": "reverse", "mode": "app", "title": { "en": "Reverse string", "fa": "وارونه‌سازی رشته" },
    "code": {
      "en": "func main:\n    s str = \"Salam\"\n    mut r str = \"\"\n    mut i i32 = s.len() - 1\n    while i >= 0:\n        r = r.concat(s.substr(i, 1))\n        i = i - 1\n    end\n    println \"reverse of\", s, \"is\", r\nend\n",
      "fa": "تابع اصلی:\n    س رشته = \"Salam\"\n    متغیر ر رشته = \"\"\n    متغیر i صحیح۳۲ = س.len() - 1\n    تاوقتی i >= 0:\n        ر = ر.concat(س.substr(i, 1))\n        i = i - 1\n    پایان\n    چاپ \"وارونه‌ی\", س, \"می‌شود\", ر\nپایان\n"
    }
  },
  {
    "id": "rectangle", "mode": "app", "title": { "en": "Struct: Rectangle", "fa": "ساختار: مستطیل" },
    "code": {
      "en": "struct Rect:\n    w f64 = 0.0\n    h f64 = 0.0\n    func area() f64: ret this.w * this.h end\n    func perimeter() f64: ret 2.0 * (this.w + this.h) end\nend\nfunc main:\n    r Rect = Rect { w = 4.0, h = 3.0 }\n    println \"area =\", r.area()\n    println \"perimeter =\", r.perimeter()\nend\n",
      "fa": "ساختار مستطیل:\n    طول اعشاری۶۴ = 0.0\n    عرض اعشاری۶۴ = 0.0\n    تابع مساحت() اعشاری۶۴: بازگشت این.طول * این.عرض پایان\n    تابع محیط() اعشاری۶۴: بازگشت 2.0 * (این.طول + این.عرض) پایان\nپایان\nتابع اصلی:\n    ر مستطیل = مستطیل { طول = 4.0, عرض = 3.0 }\n    چاپ \"مساحت =\", ر.مساحت()\n    چاپ \"محیط =\", ر.محیط()\nپایان\n"
    }
  },
  {
    "id": "wordcount", "mode": "app", "title": { "en": "Word count (HashMap)", "fa": "شمارش کلمات" },
    "code": {
      "en": "func main:\n    text str = \"the cat the dog the bird\"\n    mut words Vector<str> = text.split(\" \")\n    mut counts HashMap<str, i32> = HashMap {}\n    for mut i = 0; i < words.len(); i = i + 1:\n        w str = words.get(i)[0]\n        if counts.has(w): counts.put(w, counts.get(w) + 1)\n        else:\n            counts.put(w, 1)\n        end\n    end\n    mut it MapIter<str, i32> = counts.iter()\n    while it.has_next():\n        println it.key(), \"->\", it.value()\n        it.next()\n    end\nend\n",
      "fa": "تابع اصلی:\n    متن رشته = \"گربه سگ گربه پرنده گربه\"\n    متغیر کلمات Vector<رشته> = متن.split(\" \")\n    متغیر آمار HashMap<رشته, صحیح۳۲> = HashMap {}\n    برای متغیر i = 0; i < کلمات.len(); i = i + 1:\n        ک رشته = کلمات.get(i)[0]\n        اگر آمار.has(ک): آمار.put(ک, آمار.get(ک) + 1)\n        وگرنه:\n            آمار.put(ک, 1)\n        پایان\n    پایان\n    متغیر پیمایش MapIter<رشته, صحیح۳۲> = آمار.iter()\n    تاوقتی پیمایش.has_next():\n        چاپ پیمایش.key(), \"->\", پیمایش.value()\n        پیمایش.next()\n    پایان\nپایان\n"
    }
  },
  {
    "id": "temperature", "mode": "app", "title": { "en": "Temperature", "fa": "تبدیل دما" },
    "code": {
      "en": "func main:\n    println \"Celsius -> Fahrenheit\"\n    for mut c = 0; c <= 40; c = c + 10:\n        f f64 = (c as f64) * 9.0 / 5.0 + 32.0\n        println c, \"C =\", f, \"F\"\n    end\nend\n",
      "fa": "تابع اصلی:\n    چاپ \"سلسیوس به فارنهایت\"\n    برای متغیر س = 0; س <= 40; س = س + 10:\n        ف اعشاری۶۴ = (س بعنوان اعشاری۶۴) * 9.0 / 5.0 + 32.0\n        چاپ س, \"س =\", ف, \"ف\"\n    پایان\nپایان\n"
    }
  },
  {
    "id": "layout", "mode": "layout", "title": { "en": "Web page", "fa": "صفحه‌ی وب" },
    "code": {
      "en": "layout:\n    title = \"My Page\"\n    lang = \"english\"\n    dir = \"left to right\"\n    header:\n        background = \"blue\"\n        color = \"white\"\n        padding = \"24px\"\n        heading: size = 1 content = \"Welcome to Salam\" font_size = \"32px\" end\n    end\n    box:\n        padding = \"20px\"\n        paragraph: content = \"This page was generated from Salam.\" end\n    end\nend\n",
      "fa": "صفحه:\n    عنوان = \"برنامه‌ی من\"\n    زبان = \"فارسی\"\n    جهت = \"راست به چپ\"\n    سرصفحه:\n        پس‌زمینه = \"آبی\"\n        رنگ = \"سفید\"\n        فاصله داخلی = \"24px\"\n        سرتیتر: اندازه = 1 محتوا = \"به سلام خوش آمدید\" پایان\n    پایان\n    جعبه:\n        فاصله داخلی = \"20px\"\n        بند: محتوا = \"این صفحه از کد سلام ساخته شده است.\" پایان\n    پایان\nپایان\n"
    }
  },
  {
    "id": "collatz", "mode": "app", "title": { "en": "Collatz", "fa": "دنباله‌ی کولاتز" },
    "code": {
      "en": "func main:\n    mut n i32 = 27\n    mut steps i32 = 0\n    println \"Collatz from\", n\n    while n != 1:\n        if n % 2 == 0: n = n / 2\n        else:\n            n = 3 * n + 1\n        end\n        steps = steps + 1\n    end\n    println \"reached 1 in\", steps, \"steps\"\nend\n",
      "fa": "تابع اصلی:\n    متغیر ن صحیح۳۲ = 27\n    متغیر گامها صحیح۳۲ = 0\n    چاپ \"کولاتز از\", ن\n    تاوقتی ن != 1:\n        اگر ن % 2 == 0: ن = ن / 2\n        وگرنه:\n            ن = 3 * ن + 1\n        پایان\n        گامها = گامها + 1\n    پایان\n    چاپ \"در\", گامها, \"گام به ۱ رسید\"\nپایان\n"
    }
  },
  {
    "id": "lcm", "mode": "app", "title": { "en": "LCM", "fa": "ک.م.م" },
    "code": {
      "en": "func gcd(a i32, b i32) i32:\n    mut x i32 = a\n    mut y i32 = b\n    while y != 0:\n        mut t i32 = y\n        y = x % y\n        x = t\n    end\n    ret x\nend\nfunc lcm(a i32, b i32) i32: ret a / gcd(a, b) * b end\nfunc main:\n    println \"lcm(4, 6) =\", lcm(4, 6)\n    println \"lcm(21, 6) =\", lcm(21, 6)\nend\n",
      "fa": "تابع بمم(الف صحیح۳۲, ب صحیح۳۲) صحیح۳۲:\n    متغیر ایکس صحیح۳۲ = الف\n    متغیر ایگرگ صحیح۳۲ = ب\n    تاوقتی ایگرگ != 0:\n        متغیر ت صحیح۳۲ = ایگرگ\n        ایگرگ = ایکس % ایگرگ\n        ایکس = ت\n    پایان\n    بازگشت ایکس\nپایان\nتابع کمم(الف صحیح۳۲, ب صحیح۳۲) صحیح۳۲: بازگشت الف / بمم(الف, ب) * ب پایان\nتابع اصلی:\n    چاپ \"ک.م.م ۴ و ۶ =\", کمم(4, 6)\n    چاپ \"ک.م.م ۲۱ و ۶ =\", کمم(21, 6)\nپایان\n"
    }
  },
  {
    "id": "leap_year", "mode": "app", "title": { "en": "Leap year", "fa": "سال کبیسه" },
    "code": {
      "en": "func is_leap(y i32) bool:\n    if y % 400 == 0: ret true end\n    if y % 100 == 0: ret false end\n    ret y % 4 == 0\nend\nfunc main:\n    mut years i32[5] = [1900, 2000, 2012, 2021, 2024]\n    for mut i = 0; i < 5; i = i + 1:\n        if is_leap(years[i]): println years[i], \"is a leap year\"\n        else:\n            println years[i], \"is not a leap year\"\n        end\n    end\nend\n",
      "fa": "تابع کبیسه_است(سال صحیح۳۲) منطقی:\n    اگر سال % 400 == 0: بازگشت درست پایان\n    اگر سال % 100 == 0: بازگشت نادرست پایان\n    بازگشت سال % 4 == 0\nپایان\nتابع اصلی:\n    متغیر سالها صحیح۳۲[5] = [1900, 2000, 2012, 2021, 2024]\n    برای متغیر i = 0; i < 5; i = i + 1:\n        اگر کبیسه_است(سالها[i]): چاپ سالها[i], \"کبیسه است\"\n        وگرنه:\n            چاپ سالها[i], \"کبیسه نیست\"\n        پایان\n    پایان\nپایان\n"
    }
  },
  {
    "id": "palindrome", "mode": "app", "title": { "en": "Palindrome number", "fa": "عدد متقارن" },
    "code": {
      "en": "func is_palindrome(n i32) bool:\n    mut x i32 = n\n    mut rev i32 = 0\n    while x > 0:\n        rev = rev * 10 + x % 10\n        x = x / 10\n    end\n    ret rev == n\nend\nfunc main:\n    mut nums i32[4] = [121, 123, 1221, 13]\n    for mut i = 0; i < 4; i = i + 1:\n        if is_palindrome(nums[i]): println nums[i], \"is a palindrome\"\n        else:\n            println nums[i], \"is not a palindrome\"\n        end\n    end\nend\n",
      "fa": "تابع متقارن_است(ن صحیح۳۲) منطقی:\n    متغیر ایکس صحیح۳۲ = ن\n    متغیر وارون صحیح۳۲ = 0\n    تاوقتی ایکس > 0:\n        وارون = وارون * 10 + ایکس % 10\n        ایکس = ایکس / 10\n    پایان\n    بازگشت وارون == ن\nپایان\nتابع اصلی:\n    متغیر اعداد صحیح۳۲[4] = [121, 123, 1221, 13]\n    برای متغیر i = 0; i < 4; i = i + 1:\n        اگر متقارن_است(اعداد[i]): چاپ اعداد[i], \"متقارن است\"\n        وگرنه:\n            چاپ اعداد[i], \"متقارن نیست\"\n        پایان\n    پایان\nپایان\n"
    }
  },
  {
    "id": "digit_sum", "mode": "app", "title": { "en": "Digit sum", "fa": "جمع ارقام" },
    "code": {
      "en": "func digit_sum(n i32) i32:\n    mut x i32 = n\n    mut s i32 = 0\n    while x > 0:\n        s = s + x % 10\n        x = x / 10\n    end\n    ret s\nend\nfunc main:\n    println \"digit sum of 12345 =\", digit_sum(12345)\n    println \"digit sum of 99 =\", digit_sum(99)\nend\n",
      "fa": "تابع جمع_ارقام(ن صحیح۳۲) صحیح۳۲:\n    متغیر ایکس صحیح۳۲ = ن\n    متغیر مجموع صحیح۳۲ = 0\n    تاوقتی ایکس > 0:\n        مجموع = مجموع + ایکس % 10\n        ایکس = ایکس / 10\n    پایان\n    بازگشت مجموع\nپایان\nتابع اصلی:\n    چاپ \"جمع ارقام ۱۲۳۴۵ =\", جمع_ارقام(12345)\n    چاپ \"جمع ارقام ۹۹ =\", جمع_ارقام(99)\nپایان\n"
    }
  },
  {
    "id": "minmax", "mode": "app", "title": { "en": "Min & max", "fa": "کمینه و بیشینه" },
    "code": {
      "en": "func main:\n    mut a i32[7] = [5, 9, 1, 7, 3, 8, 2]\n    mut lo i32 = a[0]\n    mut hi i32 = a[0]\n    for mut i = 1; i < 7; i = i + 1:\n        if a[i] < lo: lo = a[i] end\n        if a[i] > hi: hi = a[i] end\n    end\n    println \"min =\", lo, \"max =\", hi\nend\n",
      "fa": "تابع اصلی:\n    متغیر آ صحیح۳۲[7] = [5, 9, 1, 7, 3, 8, 2]\n    متغیر کمینه صحیح۳۲ = آ[0]\n    متغیر بیشینه صحیح۳۲ = آ[0]\n    برای متغیر i = 1; i < 7; i = i + 1:\n        اگر آ[i] < کمینه: کمینه = آ[i] پایان\n        اگر آ[i] > بیشینه: بیشینه = آ[i] پایان\n    پایان\n    چاپ \"کمینه =\", کمینه, \"بیشینه =\", بیشینه\nپایان\n"
    }
  },
  {
    "id": "average", "mode": "app", "title": { "en": "Average", "fa": "میانگین" },
    "code": {
      "en": "func main:\n    mut a i32[6] = [10, 20, 30, 40, 50, 60]\n    mut sum i32 = 0\n    for mut i = 0; i < 6; i = i + 1: sum = sum + a[i] end\n    avg f64 = (sum as f64) / 6.0\n    println \"sum =\", sum\n    println \"average =\", avg\nend\n",
      "fa": "تابع اصلی:\n    متغیر آ صحیح۳۲[6] = [10, 20, 30, 40, 50, 60]\n    متغیر مجموع صحیح۳۲ = 0\n    برای متغیر i = 0; i < 6; i = i + 1: مجموع = مجموع + آ[i] پایان\n    میانگین اعشاری۶۴ = (مجموع بعنوان اعشاری۶۴) / 6.0\n    چاپ \"مجموع =\", مجموع\n    چاپ \"میانگین =\", میانگین\nپایان\n"
    }
  },
  {
    "id": "count_vowels", "mode": "app", "title": { "en": "Count vowels", "fa": "شمارش مصوت‌ها" },
    "code": {
      "en": "func main:\n    s str = \"salam donya\"\n    mut count i32 = 0\n    for mut i = 0; i < s.len(); i = i + 1:\n        c str = s.substr(i, 1)\n        if c == \"a\" || c == \"e\" || c == \"i\" || c == \"o\" || c == \"u\":\n            count = count + 1\n        end\n    end\n    println \"vowels in\", s, \"=\", count\nend\n",
      "fa": "تابع اصلی:\n    س رشته = \"salam donya\"\n    متغیر تعداد صحیح۳۲ = 0\n    برای متغیر i = 0; i < س.len(); i = i + 1:\n        ک رشته = س.substr(i, 1)\n        اگر ک == \"a\" || ک == \"e\" || ک == \"i\" || ک == \"o\" || ک == \"u\":\n            تعداد = تعداد + 1\n        پایان\n    پایان\n    چاپ \"تعداد مصوت‌ها در\", س, \"=\", تعداد\nپایان\n"
    }
  },
  {
    "id": "star_triangle", "mode": "app", "title": { "en": "Star triangle", "fa": "مثلث ستاره" },
    "code": {
      "en": "func main:\n    for mut row = 1; row <= 5; row = row + 1:\n        mut line str = \"\"\n        for mut col = 0; col < row; col = col + 1: line = line + \"*\" end\n        println line\n    end\nend\n",
      "fa": "تابع اصلی:\n    برای متغیر ردیف = 1; ردیف <= 5; ردیف = ردیف + 1:\n        متغیر خط رشته = \"\"\n        برای متغیر ستون = 0; ستون < ردیف; ستون = ستون + 1: خط = خط + \"*\" پایان\n        چاپ خط\n    پایان\nپایان\n"
    }
  },
  {
    "id": "multiplication_table", "mode": "app", "title": { "en": "Times table", "fa": "جدول ضرب" },
    "code": {
      "en": "func main:\n    for mut i = 1; i <= 5; i = i + 1:\n        mut line str = \"\"\n        for mut j = 1; j <= 5; j = j + 1: line = line + (i * j) + \" \" end\n        println line\n    end\nend\n",
      "fa": "تابع اصلی:\n    برای متغیر i = 1; i <= 5; i = i + 1:\n        متغیر خط رشته = \"\"\n        برای متغیر j = 1; j <= 5; j = j + 1: خط = خط + (i * j) + \" \" پایان\n        چاپ خط\n    پایان\nپایان\n"
    }
  },
  {
    "id": "dec_to_bin", "mode": "app", "title": { "en": "Decimal to binary", "fa": "تبدیل به دودویی" },
    "code": {
      "en": "func to_binary(n i32) str:\n    if n == 0: ret \"0\" end\n    mut x i32 = n\n    mut bits str = \"\"\n    while x > 0:\n        bits = \"\" + (x % 2) + bits\n        x = x / 2\n    end\n    ret bits\nend\nfunc main:\n    mut nums i32[4] = [0, 5, 10, 255]\n    for mut i = 0; i < 4; i = i + 1:\n        println nums[i], \"=\", to_binary(nums[i]), \"in binary\"\n    end\nend\n",
      "fa": "تابع به_دودویی(ن صحیح۳۲) رشته:\n    اگر ن == 0: بازگشت \"0\" پایان\n    متغیر ایکس صحیح۳۲ = ن\n    متغیر بیتها رشته = \"\"\n    تاوقتی ایکس > 0:\n        بیتها = \"\" + (ایکس % 2) + بیتها\n        ایکس = ایکس / 2\n    پایان\n    بازگشت بیتها\nپایان\nتابع اصلی:\n    متغیر اعداد صحیح۳۲[4] = [0, 5, 10, 255]\n    برای متغیر i = 0; i < 4; i = i + 1:\n        چاپ اعداد[i], \"در مبنای دو =\", به_دودویی(اعداد[i])\n    پایان\nپایان\n"
    }
  },
  {
    "id": "prime_factors", "mode": "app", "title": { "en": "Prime factors", "fa": "عوامل اول" },
    "code": {
      "en": "func main:\n    mut n i32 = 360\n    mut x i32 = n\n    mut line str = \"\"\n    mut d i32 = 2\n    while d * d <= x:\n        while x % d == 0:\n            line = line + d + \" \"\n            x = x / d\n        end\n        d = d + 1\n    end\n    if x > 1: line = line + x + \" \" end\n    println n, \"=\", line\nend\n",
      "fa": "تابع اصلی:\n    متغیر ن صحیح۳۲ = 360\n    متغیر ایکس صحیح۳۲ = ن\n    متغیر خط رشته = \"\"\n    متغیر د صحیح۳۲ = 2\n    تاوقتی د * د <= ایکس:\n        تاوقتی ایکس % د == 0:\n            خط = خط + د + \" \"\n            ایکس = ایکس / د\n        پایان\n        د = د + 1\n    پایان\n    اگر ایکس > 1: خط = خط + ایکس + \" \" پایان\n    چاپ ن, \"=\", خط\nپایان\n"
    }
  },
  {
    "id": "power_iter", "mode": "app", "title": { "en": "Integer power", "fa": "توان صحیح" },
    "code": {
      "en": "func power(base i32, exp i32) i32:\n    mut result i32 = 1\n    for mut i = 0; i < exp; i = i + 1: result = result * base end\n    ret result\nend\nfunc main:\n    for mut e = 0; e <= 8; e = e + 1:\n        println \"2 ^\", e, \"=\", power(2, e)\n    end\nend\n",
      "fa": "تابع توان(پایه صحیح۳۲, نما صحیح۳۲) صحیح۳۲:\n    متغیر نتیجه صحیح۳۲ = 1\n    برای متغیر i = 0; i < نما; i = i + 1: نتیجه = نتیجه * پایه پایان\n    بازگشت نتیجه\nپایان\nتابع اصلی:\n    برای متغیر e = 0; e <= 8; e = e + 1:\n        چاپ \"۲ به توان\", e, \"=\", توان(2, e)\n    پایان\nپایان\n"
    }
  },
  {
    "id": "bank_account", "mode": "app", "title": { "en": "Bank account", "fa": "حساب بانکی" },
    "code": {
      "en": "struct Account:\n    balance i32 = 0\n    func deposit(n i32): this.balance = this.balance + n end\n    func withdraw(n i32):\n        if n <= this.balance: this.balance = this.balance - n\n        else:\n            println \"insufficient funds\"\n        end\n    end\nend\nfunc main:\n    mut a Account = Account { balance = 100 }\n    a.deposit(50)\n    a.withdraw(30)\n    a.withdraw(200)\n    println \"balance =\", a.balance\nend\n",
      "fa": "ساختار حساب:\n    موجودی صحیح۳۲ = 0\n    تابع واریز(مبلغ صحیح۳۲): این.موجودی = این.موجودی + مبلغ پایان\n    تابع برداشت(مبلغ صحیح۳۲):\n        اگر مبلغ <= این.موجودی: این.موجودی = این.موجودی - مبلغ\n        وگرنه:\n            چاپ \"موجودی کافی نیست\"\n        پایان\n    پایان\nپایان\nتابع اصلی:\n    متغیر ح حساب = حساب { موجودی = 100 }\n    ح.واریز(50)\n    ح.برداشت(30)\n    ح.برداشت(200)\n    چاپ \"موجودی =\", ح.موجودی\nپایان\n"
    }
  },
  {
    "id": "stack", "mode": "app", "title": { "en": "Stack", "fa": "پشته" },
    "code": {
      "en": "func main:\n    mut s Vector<i32> = Vector {}\n    s.push(1)\n    s.push(2)\n    s.push(3)\n    println \"size =\", s.len()\n    while s.len() > 0:\n        println \"pop\", s.pop()\n    end\n    println \"size =\", s.len()\nend\n",
      "fa": "تابع اصلی:\n    متغیر پشته Vector<صحیح۳۲> = Vector {}\n    پشته.push(1)\n    پشته.push(2)\n    پشته.push(3)\n    چاپ \"اندازه =\", پشته.len() بعنوان صحیح۳۲\n    تاوقتی پشته.len() > 0:\n        چاپ \"برداشت\", پشته.pop()\n    پایان\n    چاپ \"اندازه =\", پشته.len() بعنوان صحیح۳۲\nپایان\n"
    }
  },
  {
    "id": "weekday", "mode": "app", "title": { "en": "Weekdays (enum)", "fa": "روزهای هفته" },
    "code": {
      "en": "enum Day: Mon, Tue, Wed, Thu, Fri, Sat, Sun end\nfunc is_weekend(d Day) bool: ret d == Day.Sat || d == Day.Sun end\nfunc main:\n    d Day = Day.Sat\n    println \"day index =\", d as i32\n    if is_weekend(d): println \"it is the weekend\"\n    else:\n        println \"it is a weekday\"\n    end\nend\n",
      "fa": "شمارش روز: دوشنبه, سه‌شنبه, چهارشنبه, پنجشنبه, جمعه, شنبه, یکشنبه پایان\nتابع آخرهفته_است(ر روز) منطقی: بازگشت ر == روز.شنبه || ر == روز.یکشنبه پایان\nتابع اصلی:\n    ر روز = روز.شنبه\n    چاپ \"شماره‌ی روز =\", ر بعنوان صحیح۳۲\n    اگر آخرهفته_است(ر): چاپ \"آخر هفته است\"\n    وگرنه:\n        چاپ \"روز کاری است\"\n    پایان\nپایان\n"
    }
  },
  {
    "id": "counter_closure", "mode": "app", "title": { "en": "Counter closure", "fa": "بستار شمارنده" },
    "code": {
      "en": "func make_counter() func () i32:\n    mut n i32 = 0\n    ret () =>:\n        n = n + 1\n        ret n\n    end\nend\nfunc main:\n    next func () i32 = make_counter()\n    println next(), next(), next(), next()\nend\n",
      "fa": "تابع ساخت_شمارنده() func () صحیح۳۲:\n    متغیر ن صحیح۳۲ = 0\n    بازگشت () =>:\n        ن = ن + 1\n        بازگشت ن\n    پایان\nپایان\nتابع اصلی:\n    بعدی func () صحیح۳۲ = ساخت_شمارنده()\n    چاپ بعدی(), بعدی(), بعدی(), بعدی()\nپایان\n"
    }
  },
  {
    "id": "acronym", "mode": "app", "title": { "en": "Acronym", "fa": "سرنام" },
    "code": {
      "en": "func main:\n    phrase str = \"salam azad multi platform\"\n    mut words Vector<str> = phrase.split(\" \")\n    mut acro str = \"\"\n    for mut i = 0; i < words.len(); i = i + 1:\n        w str = words.get(i)[0]\n        acro = acro + w.substr(0, 1)\n    end\n    println phrase, \"->\", acro\nend\n",
      "fa": "تابع اصلی:\n    عبارت رشته = \"salam azad multi platform\"\n    متغیر کلمات Vector<رشته> = عبارت.split(\" \")\n    متغیر سرنام رشته = \"\"\n    برای متغیر i = 0; i < کلمات.len(); i = i + 1:\n        ک رشته = کلمات.get(i)[0]\n        سرنام = سرنام + ک.substr(0, 1)\n    پایان\n    چاپ عبارت, \"->\", سرنام\nپایان\n"
    }
  },
  {
    "id": "sqrt_newton", "mode": "app", "title": { "en": "Newton sqrt", "fa": "جذر نیوتن" },
    "code": {
      "en": "func sqrt(x f64) f64:\n    if x <= 0.0: ret 0.0 end\n    mut guess f64 = x\n    for mut i = 0; i < 20; i = i + 1:\n        guess = (guess + x / guess) / 2.0\n    end\n    ret guess\nend\nfunc main:\n    mut vals f64[3] = [2.0, 16.0, 50.0]\n    for mut i = 0; i < 3; i = i + 1:\n        println \"sqrt of\", vals[i], \"~\", sqrt(vals[i])\n    end\nend\n",
      "fa": "تابع جذر(ایکس اعشاری۶۴) اعشاری۶۴:\n    اگر ایکس <= 0.0: بازگشت 0.0 پایان\n    متغیر حدس اعشاری۶۴ = ایکس\n    برای متغیر i = 0; i < 20; i = i + 1:\n        حدس = (حدس + ایکس / حدس) / 2.0\n    پایان\n    بازگشت حدس\nپایان\nتابع اصلی:\n    متغیر مقادیر اعشاری۶۴[3] = [2.0, 16.0, 50.0]\n    برای متغیر i = 0; i < 3; i = i + 1:\n        چاپ \"جذر\", مقادیر[i], \"تقریباً\", جذر(مقادیر[i])\n    پایان\nپایان\n"
    }
  },
  {
    "id": "range_sum", "mode": "app", "title": { "en": "Range sum", "fa": "مجموع بازه" },
    "code": {
      "en": "func main:\n    mut n i32 = 100\n    mut sum i32 = 0\n    for mut i = 1; i <= n; i = i + 1: sum = sum + i end\n    formula i32 = n * (n + 1) / 2\n    println \"loop sum =\", sum\n    println \"formula  =\", formula\nend\n",
      "fa": "تابع اصلی:\n    متغیر ن صحیح۳۲ = 100\n    متغیر مجموع صحیح۳۲ = 0\n    برای متغیر i = 1; i <= ن; i = i + 1: مجموع = مجموع + i پایان\n    فرمول صحیح۳۲ = ن * (ن + 1) / 2\n    چاپ \"مجموع حلقه =\", مجموع\n    چاپ \"مجموع فرمول =\", فرمول\nپایان\n"
    }
  }
];
