# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_stages = [
  "pre-commit",
  "pre-push"
  ]
default_language_version = { python = "python3" }
minimum_prek_version = "0.3.4"

[[repos]]
repo = "meta"
hooks = [
  {
    id = "identity",
    name = "run identity check",
    description = "check you have set your git identity",
    priority = 10
  },
  {
    id = "check-hooks-apply",
    name = "run check hooks apply",
    description = "check that all the hooks apply to the repository",
    priority = 10
  }
]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "83d9cd684c87d95d656c1458ef04895a7f1cbd8e"
hooks = [
  {
    id = "gitleaks",
    name = "run gitleaks",
    description = "check for secrets with gitleaks",
    priority = 50
  }
]
