# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_stages = [
  "pre-commit",
  "pre-push"
  ]
default_language_version = { python = "python3" }
minimum_prek_version = "0.3.4"

[[repos]]
repo = "meta"
hooks = [
  {
    id = "identity",
    name = "run identity check",
    description = "check you have set your git identity",
    priority = 10
  },
  {
    id = "check-hooks-apply",
    name = "run check hooks apply",
    description = "check that all the hooks apply to the repository",
    priority = 10
  }
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "bun-audit",
    name = "run bun audit",
    description = "check installed packages for known security vulnerabilities with bun audit",
    priority = 50,
    entry = "bun audit",
    files = '^(bun\.lock|bunfig\.toml|package\.json)$',
    language = "system",
    pass_filenames = false
  }
]
