#ifndef _SRC_UTILITY_STRING_STRING_HASH_STRING_HASH_H_
#define _SRC_UTILITY_STRING_STRING_HASH_STRING_HASH_H_

unsigned long string_hash(const char* str);

#endif // _SRC_UTILITY_STRING_STRING_HASH_STRING_HASH_H_
