#ifndef _SRC_STAGE_AST_ASTS_AST_PARAMETER_AST_PARAMETER_ITEM_AST_PARAMETER_ITEM_DIRECT_DESTROY_AST_PARAMETER_ITEM_DIRECT_DESTROY_H_
#define _SRC_STAGE_AST_ASTS_AST_PARAMETER_AST_PARAMETER_ITEM_AST_PARAMETER_ITEM_DIRECT_DESTROY_AST_PARAMETER_ITEM_DIRECT_DESTROY_H_

// base
#include <base.h>

// memory
#include <utility/memory/memory_destroy/memory_destroy.h>

// array
#include <utility/array/type.h>
#include <utility/array/array_destroy/array_destroy.h>

void ast_parameter_item_direct_destroy(ast_parameter_item_t parameter_item);

#endif // _SRC_STAGE_AST_ASTS_AST_PARAMETER_AST_PARAMETER_ITEM_AST_PARAMETER_ITEM_DIRECT_DESTROY_AST_PARAMETER_ITEM_DIRECT_DESTROY_H_
