#include "core/prelude.h"
#include "cli/options.h"

void cli_print_usage(FILE *out)
{
    fprintf(out,
        "salamc - Salam compiler\n"
        "\n"
        "Usage:\n"
        "  salamc <command> [arguments] [options]\n"
        "  salamc <input.salam> [inspect options]\n"
        "\n"
        "Commands:\n"
        "  build    <files...> [build options]           Compile to an executable\n"
        "  obj      <files...> [build options]           Compile to an object file\n"
        "  llvm     <file.salam> [--output=FILE]         Emit LLVM IR (.ll) for the LLVM/wasm backend\n"
        "  run      [file.salam] [build options]         Build (auto-detect entry) + run, no artifacts kept\n"
        "  exec     [file.salam]                          Run with the tree-walking interpreter (no C toolchain)\n"
        "  new      [name] [--lang=en|fa]                Scaffold a new project directory\n"
        "  fmt      [files/dirs...] [--check] [-r] [--tabs]  Format .salam source in place (recursive)\n"
        "  layout   build <files...> [--inline]          Build the layout DSL to HTML/CSS/JS\n"
        "  debug    <file.salam> [build options]         Build -g + launch GDB/LLDB\n"
        "  memcheck <file.salam> [build options]         Build ASAN + run memory checker\n"
        "  cli                                           Start the general REPL\n"
        "  layout                                        Start the layout REPL\n"
        "  help                                          Show this help\n"
        "  version                                       Show the compiler version\n"
        "\n"
        "Build options:\n"
        "  --output=FILE            Output executable (default: <module>.exe)\n"
        "  --cc=PATH                C compiler to invoke (default: tcc)\n"
        "  --stdlib-path=DIR        Root directory for 'std/...' imports\n"
        "  --keep-c                 Keep generated .c/.h files\n"
        "  -g, --debug-info         Embed DWARF debug symbols; emit #line directives\n"
        "  --asan                   Enable AddressSanitizer (requires gcc/clang)\n"
        "\n"
        "LLVM backend options (salamc llvm <file>):\n"
        "  -O0|-O1|-O2|-O3|-Os|-Oz   Optimization level (default -O0)\n"
        "  --emit-llvm               Emit textual LLVM IR (.ll) [default]\n"
        "  --emit-asm                Emit target assembly (.s)\n"
        "  --emit-obj, -c            Emit an object file (.o)\n"
        "  --emit-bitcode, -flto     Emit LLVM bitcode (.bc) for LTO\n"
        "  --exec                    Build a native executable (links libc/m)\n"
        "  --jit                     JIT-run immediately via lli (no artifact)\n"
        "  --target=TRIPLE           Cross-compile target (e.g. wasm32-wasi)\n"
        "  -g                        Emit DWARF debug info into the IR\n"
        "  --verify-ir               Run the LLVM verifier before emitting\n"
        "  -o FILE                   Output path (default: derived from module)\n"
        "\n"
        "Format options:\n"
        "  --check                  Report files that need formatting; do not rewrite (exit 1 if any)\n"
        "  -r, --recursive          Recurse into directories (implied when no path is given)\n"
        "  --tabs                   Indent with one tab per level (convert spaces to tabs)\n"
        "  --spaces                 Indent with spaces (default)\n"
        "  --indent=tab|N           Indent style: 'tab', or N spaces per level (1-16, default 4)\n"
        "  --lang=CODE              Language pack of the source (use fa for Persian files)\n"
        "\n"
        "Inspect options:\n"
        "  --emit-tokens-xml        Emit the token stream as XML\n"
        "  --emit-ast-xml           Lex + parse + analyze, emit the decorated AST as XML\n"
        "  --emit-symbol-xml        Lex + parse + analyze, emit the symbol table as XML\n"
        "  --xml-out=FILE           Write XML to FILE (default: stdout)\n"
        "  --log-level=LEVEL        trace|debug|info|warn|error|off (default: info)\n"
        "  --lang=CODE              Language pack (default: en)\n"
        "  --color / --no-color     Force or disable colored logs (default: auto)\n"
        "  --error-style=STYLE      rust|gcc|clang (default: rust)\n"
        "  --error-format=FORMAT    human|json|xml (default: human)\n");
}
