" Vim syntax file - Language: Salam
" Generated by extensions/tools/gen_syntaxes.salam

if exists('b:current_syntax')
  finish
endif

let s:cpo_save = &cpo
set cpo&vim

if has('patch-7.4.1142')
  syn iskeyword @,48-57,_,192-255,1536-1791,1872-1919,2208-2303,64336-65023,65136-65279,8204,8205
else
  setlocal iskeyword=@,48-57,_,192-255,1536-1791,1872-1919,2208-2303,64336-65023,65136-65279,8204,8205
endif

syn case match
syn sync minlines=60 maxlines=400

syn keyword salamConditional  if else match اگر وگرنه تطبیق إذا وإلا طابق
syn keyword salamRepeat       until repeat each while تاوقتی تکرار هر بينما كرر كل
syn keyword salamStatement    ret end break continue defer to by in with بازگشت تمام بشکن ادامه تعلیق تا گام در با أرجع نهاية اكسر واصل أجل إلى خطوة في مع
syn keyword salamStorageClass mut const extern pub inline noinline pure noret deprecated متغیر ثابت خارجی عمومی درون‌خطی غیردرون‌خطی خالص بی‌بازگشت منسوخ متغير خارجي عام مضمن غيرمضمن نقي لايرجع مهجور
syn keyword salamKeyword      on as layout operator impl بر بعنوان صفحه عملگر پیاده‌سازی على بوصفه صفحة عامل تنفيذ
syn keyword salamBoolean      true false درست نادرست صواب خطأ
syn keyword salamNull         null پوچ عدم
syn keyword salamThis         this این هذا
syn keyword salamType         void bool char str uchar i8 i16 i32 int i64 u8 u16 u32 uint u64 size f32 float f64 تهی منطقی نویسه رشته یونیکد صحیح۸ صحیح۱۶ صحیح۳۲ صحیح صحیح۶۴ صحیح8 صحیح16 صحیح32 صحیح64 طبیعی۸ طبیعی۱۶ طبیعی۳۲ طبیعی طبیعی۶۴ طبیعی8 طبیعی16 طبیعی32 طبیعی64 اندازه اعشار۳۲ اعشار اعشار۶۴ اعشار32 اعشار64 فراغ منطقي حرف نص يونيكود صحيح٨ صحيح١٦ صحيح٣٢ صحيح صحيح٦٤ صحيح8 صحيح16 صحيح32 صحيح64 طبيعي٨ طبيعي١٦ طبيعي٣٢ طبيعي طبيعي٦٤ طبيعي8 طبيعي16 طبيعي32 طبيعي64 حجم عشري٣٢ عشري عشري٦٤ عشري32 عشري64
syn keyword salamType         auto خودکار تلقائي
syn keyword salamBuiltinType  وکتور متجه Vector نگاشت خريطة HashMap پیمایشگرنگاشت مكررخريطة MapIter پرونده ملف File گوناگون متنوع Variant
syn keyword salamBuiltin      print println printerr printerrln input بنویس چاپ خطابنویس خطاچاپ بخوان اكتب اطبع اكتبخطأ اطبعخطأ اقرأ
syn keyword salamOperatorWord و یا أو
syn keyword salamContextual   link static dynamic framework kind پیوند ایستا پویا چارچوب گونه رابط ساكن ديناميكي إطار صنف dyn

syn keyword salamFuncDecl  func تابع دالة nextgroup=salamFunctionName skipwhite
syn keyword salamStructure type struct enum interface component نوع ساختار شمارش واسط مولفه بنية تعداد واجهة مكون nextgroup=salamTypeName skipwhite
syn keyword salamInclude   import package واردکردن بسته استيراد حزمة nextgroup=salamModuleName skipwhite

syn match salamFunctionName contained "\k\+"
syn match salamTypeName     contained "\k\+"
syn match salamModuleName   contained "\k\+\%(\.\k\+\)*"

syn match salamNumber "\<[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*f\=\>"
syn match salamNumber "\<0[xX]\x[0-9A-Fa-f_]*\>"
syn match salamNumber "\<0[bB][01][01_]*\>"
syn match salamNumber "\<0[oO]\o[0-7_]*\>"
syn match salamFloat  "\<[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*[eE][+-]\=[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*f\=\>"
syn match salamFloat  "\<[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*\.[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*\%([eE][+-]\=[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*\)\=f\=\>"

syn match salamAnnotation "@[A-Za-z_]\k*"
syn match salamLayoutElement "^\s*\%(\%(غیردرون‌خطی\|deprecated\|پیاده‌سازی\|printerrln\|interface\|component\|بی‌بازگشت\|continue\|operator\|noinline\|واردکردن\|درون‌خطی\|printerr\|خطابنویس\|package\|استيراد\|غيرمضمن\|println\|اكتبخطأ\|اطبعخطأ\|repeat\|بازگشت\|تاوقتی\|struct\|import\|layout\|extern\|inline\|ساختار\|بعنوان\|لايرجع\|نادرست\|خطاچاپ\|until\|break\|defer\|match\|while\|وگرنه\|ادامه\|تعلیق\|تکرار\|تطبیق\|بينما\|نهاية\|const\|noret\|متغیر\|شمارش\|عملگر\|خارجی\|عمومی\|منسوخ\|مولفه\|متغير\|تعداد\|بوصفه\|خارجي\|واجهة\|مهجور\|تنفيذ\|false\|print\|input\|بنویس\|بخوان\|else\|each\|with\|تمام\|بشکن\|أرجع\|وإلا\|اكسر\|واصل\|خطوة\|طابق\|func\|type\|enum\|pure\|impl\|تابع\|ثابت\|صفحه\|بسته\|واسط\|خالص\|دالة\|بنية\|صفحة\|حزمة\|عامل\|مضمن\|مكون\|true\|null\|درست\|صواب\|this\|اكتب\|اطبع\|اقرأ\|ret\|end\|اگر\|گام\|إذا\|أجل\|كرر\|إلى\|mut\|pub\|نوع\|على\|عام\|نقي\|پوچ\|خطأ\|عدم\|این\|هذا\|چاپ\|if\|to\|by\|in\|تا\|هر\|در\|با\|كل\|في\|مع\|on\|as\|بر\|یا\|أو\|و\)\>\)\@!\zs\k\+\ze\s*:\s*$"

syn match salamOperator "=>\|\.\.\.\|:=\|==\|!=\|<=\|>=\|&&\|||\|\^\^=\|[-+*/%]=\|[-+*/%<>=!&?]"
syn match salamDelimiter "[(){}\[\],;]"

syn match salamEscape      contained "\\\%(x\x\x\|u{\x\+}\|u\x\{4}\|[0abfnrtv\"'\\]\)"
syn match salamEscapeError contained "\\\%(x\x\x\|u{\x\+}\|u\x\{4}\|[0abfnrtv\"'\\]\)\@!."

syn region salamString start=+"+ skip=+\\\\\|\\"+ end=+"+ oneline
      \ contains=salamEscape,salamEscapeError,@Spell
syn region salamRawString start=+`+ end=+`+ contains=@Spell
syn region salamTripleString start=+"""+ end=+"""+ keepend
      \ contains=salamEscape,salamEscapeError,@Spell
syn match  salamCharacter "u\='\%(\\\%(x\x\x\|u{\x\+}\|u\x\{4}\|.\)\|[^'\\]\)'"

syn match salamFunctionCall "\k\+\ze\s*("
syn match salamBuiltinMethod "\.\@<=\%(خواندن خط\|داردبعدی\|يوجدتالي\|has_next\|قراءةسطر\|readline\|به اعشار\|to_float\|دربیاور\|جابجایی\|زیررشته\|به صحیح\|إلىصحيح\|إلىعشري\|آزادکن\|remove\|اندازه\|پیمایش\|التالي\|خواندن\|انتقال\|concat\|substr\|پیراست\|to_int\|بیفزا\|ارجاع\|بنشان\|ظرفیت\|تكرار\|مفتاح\|مقدار\|value\|قراءة\|نوشتن\|كتابة\|write\|close\|پیوست\|بشکاف\|split\|push\|أخرج\|بگیر\|احصل\|مرجع\|free\|دارد\|يحوي\|احذف\|size\|iter\|کلید\|قيمة\|بعدی\|next\|read\|seek\|ببند\|أغلق\|مقطع\|بیاب\|ابحث\|find\|trim\|أضف\|pop\|get\|ref\|عين\|set\|طول\|len\|سعة\|cap\|حرر\|درج\|put\|has\|حذف\|حجم\|key\|دمج\|قسم\|شذب\|ضع\)\>"

syn keyword salamTodo contained TODO FIXME XXX NOTE HACK
syn region  salamBlockComment start="/\*" end="\*/" contains=salamTodo,@Spell fold
syn region  salamComment start="//" end="$" keepend oneline contains=salamTodo,@Spell
syn match   salamDirectiveKey contained "\<\%(version\|title\|mode\|lang\|name\|dir\)\>"
syn match   salamDirectiveSep contained "|"
syn region  salamDirective start="//!" end="$" keepend oneline
      \ contains=salamDirectiveKey,salamDirectiveSep,@Spell

hi def link salamConditional   Conditional
hi def link salamRepeat        Repeat
hi def link salamStatement     Statement
hi def link salamStorageClass  StorageClass
hi def link salamStructure     Structure
hi def link salamInclude       Include
hi def link salamKeyword       Keyword
hi def link salamFuncDecl      Keyword
hi def link salamContextual    Keyword
hi def link salamBoolean       Boolean
hi def link salamNull          Constant
hi def link salamThis          Identifier
hi def link salamType          Type
hi def link salamBuiltinType   Type
hi def link salamTypeName      Type
hi def link salamFunctionName  Function
hi def link salamFunctionCall  Function
hi def link salamBuiltin       Function
hi def link salamBuiltinMethod Function
hi def link salamModuleName    Identifier
hi def link salamLayoutElement Identifier
hi def link salamComment       Comment
hi def link salamBlockComment  Comment
hi def link salamTodo          Todo
hi def link salamDirective     PreProc
hi def link salamDirectiveKey  Special
hi def link salamDirectiveSep  Delimiter
hi def link salamAnnotation    PreProc
hi def link salamString        String
hi def link salamTripleString  String
hi def link salamRawString     String
hi def link salamCharacter     Character
hi def link salamEscape        SpecialChar
hi def link salamEscapeError   Error
hi def link salamNumber        Number
hi def link salamFloat         Float
hi def link salamOperator      Operator
hi def link salamOperatorWord  Operator
hi def link salamDelimiter     Delimiter

let b:current_syntax = 'salam'

let &cpo = s:cpo_save
unlet s:cpo_save
