" Vim syntax file - Language: Salam
" Generated by extensions/tools/gen_syntaxes.salam

if exists('b:current_syntax')
  finish
endif

let s:cpo_save = &cpo
set cpo&vim

syn iskeyword @,48-57,_,192-255

syn case match
syn sync minlines=60 maxlines=400

syn keyword salamConditional  if else match اگر وگرنه برگزین
syn keyword salamRepeat       until repeat each while تاهنگام چرخه هر
syn keyword salamStatement    ret end break continue defer to by in with بازگشت پایان بشکن بگذر دیرکرد تا گام در با
syn keyword salamStorageClass mut const extern pub inline noinline pure noret deprecated گذرا پایدار خارجی همگانی توکار جدا درونزا ازکارافتاده
syn keyword salamKeyword      on as layout operator impl بر برگردان چیدمان کنشگر
syn keyword salamBoolean      true false درست نادرست
syn keyword salamNull         null پوچ
syn keyword salamThis         this این
syn keyword salamType         void bool char str uchar i8 i16 i32 int i64 u8 u16 u32 uint u64 size f32 float f64 تهی منطقی نویسه رشته یونیکد صحیح۸ صحیح۱۶ صحیح۳۲ صحیح صحیح۶۴ صحیح8 صحیح16 صحیح32 صحیح64 طبیعی۸ طبیعی۱۶ طبیعی۳۲ طبیعی طبیعی۶۴ طبیعی8 طبیعی16 طبیعی32 طبیعی64 اندازه اعشار۳۲ اعشار اعشار۶۴ اعشار32 اعشار64
syn keyword salamType         auto خودکار تلقائي
syn keyword salamBuiltinType  وکتور Vector نگاشت HashMap پیمایشگرنگاشت MapIter پرونده File گوناگون Variant
syn keyword salamBuiltin      print println printerr printerrln input بنویس چاپ نادرستینویس نادرستیچاپ بخوان
syn keyword salamOperatorWord و یا
syn keyword salamContextual   link static dynamic framework kind پیوند ایستا پویا چارچوب گونه dyn
syn match salamStorageClass "\<\%(بی‌بازگشت\)\>"
syn match salamKeyword "\<\%(پیاده‌سازی\)\>"

syn keyword salamFuncDecl  func کارکرد nextgroup=salamFunctionName skipwhite
syn keyword salamStructure type struct enum interface component ریخت ساختار شمارش واسط سازه nextgroup=salamTypeName skipwhite
syn keyword salamInclude   import package فراخوانی بسته nextgroup=salamModuleName skipwhite

syn match salamFunctionName contained "\k\+"
syn match salamTypeName     contained "\k\+"
syn match salamModuleName   contained "\k\+\%(\.\k\+\)*"

syn match salamNumber "\<[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*f\=\>"
syn match salamNumber "\<0[xX]\x[0-9A-Fa-f_]*\>"
syn match salamNumber "\<0[bB][01][01_]*\>"
syn match salamNumber "\<0[oO]\o[0-7_]*\>"
syn match salamFloat  "\<[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*[eE][+-]\=[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*f\=\>"
syn match salamFloat  "\<[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*\.[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*\%([eE][+-]\=[0-9\u0660-\u0669\u06f0-\u06f9][0-9\u0660-\u0669\u06f0-\u06f9_]*\)\=f\=\>"

syn match salamAnnotation "@[A-Za-z_]\k*"
syn match salamLayoutElement "^\s*\%(\%(ازکارافتاده\|نادرستینویس\|deprecated\|پیاده‌سازی\|printerrln\|نادرستیچاپ\|interface\|component\|بی‌بازگشت\|continue\|operator\|noinline\|فراخوانی\|printerr\|تاهنگام\|package\|برگردان\|println\|repeat\|بازگشت\|دیرکرد\|برگزین\|struct\|import\|layout\|extern\|inline\|کارکرد\|پایدار\|ساختار\|چیدمان\|همگانی\|درونزا\|نادرست\|until\|break\|defer\|match\|while\|وگرنه\|پایان\|const\|noret\|شمارش\|کنشگر\|خارجی\|توکار\|false\|print\|input\|بنویس\|بخوان\|else\|each\|with\|بشکن\|بگذر\|چرخه\|func\|type\|enum\|pure\|impl\|گذرا\|ریخت\|بسته\|واسط\|سازه\|true\|null\|درست\|this\|ret\|end\|اگر\|گام\|mut\|pub\|جدا\|پوچ\|این\|چاپ\|if\|to\|by\|in\|تا\|هر\|در\|با\|on\|as\|بر\|یا\|و\)\>\)\@!\zs\k\+\ze\s*:\s*$"

syn match salamOperator "=>\|\.\.\.\|:=\|==\|!=\|<=\|>=\|&&\|||\|\^\^=\|[-+*/%]=\|[-+*/%<>=!&?]"
syn match salamDelimiter "[(){}\[\],;]"

syn match salamEscape      contained "\\\%(x\x\x\|u{\x\+}\|u\x\{4}\|[0abfnrtv\"'\\]\)"
syn match salamEscapeError contained "\\\%(x\x\x\|u{\x\+}\|u\x\{4}\|[0abfnrtv\"'\\]\)\@!."

syn region salamString start=+"+ skip=+\\\\\|\\"+ end=+"+ oneline
      \ contains=salamEscape,salamEscapeError,@Spell
syn region salamRawString start=+`+ end=+`+ contains=@Spell
syn region salamTripleString start=+"""+ end=+"""+ keepend
      \ contains=salamEscape,salamEscapeError,@Spell
syn match  salamCharacter "u\='\%(\\\%(x\x\x\|u{\x\+}\|u\x\{4}\|.\)\|[^'\\]\)'"

syn match salamFunctionCall "\k\+\ze\s*("
syn match salamBuiltinMethod "\.\@<=\%(خواندن خط\|داردبعدی\|has_next\|readline\|به اعشار\|to_float\|دربیاور\|جابجایی\|زیررشته\|به صحیح\|آزادکن\|remove\|اندازه\|پیمایش\|خواندن\|concat\|substr\|پیراست\|to_int\|بیفزا\|ارجاع\|بنشان\|ظرفیت\|مقدار\|value\|نوشتن\|write\|close\|پیوست\|بشکاف\|split\|push\|بگیر\|free\|دارد\|size\|iter\|کلید\|بعدی\|next\|read\|seek\|ببند\|بیاب\|find\|trim\|pop\|get\|ref\|set\|طول\|len\|cap\|درج\|put\|has\|حذف\|key\)\>"

syn keyword salamTodo contained TODO FIXME XXX NOTE HACK
syn region  salamBlockComment start="/\*" end="\*/" contains=salamTodo,@Spell fold
syn region  salamComment start="//" end="$" keepend oneline contains=salamTodo,@Spell
syn match   salamDirectiveKey contained "\<\%(version\|title\|mode\|lang\|name\|dir\)\>"
syn match   salamDirectiveSep contained "|"
syn region  salamDirective start="//!" end="$" keepend oneline
      \ contains=salamDirectiveKey,salamDirectiveSep,@Spell

hi def link salamConditional   Conditional
hi def link salamRepeat        Repeat
hi def link salamStatement     Statement
hi def link salamStorageClass  StorageClass
hi def link salamStructure     Structure
hi def link salamInclude       Include
hi def link salamKeyword       Keyword
hi def link salamFuncDecl      Keyword
hi def link salamContextual    Keyword
hi def link salamBoolean       Boolean
hi def link salamNull          Constant
hi def link salamThis          Identifier
hi def link salamType          Type
hi def link salamBuiltinType   Type
hi def link salamTypeName      Type
hi def link salamFunctionName  Function
hi def link salamFunctionCall  Function
hi def link salamBuiltin       Function
hi def link salamBuiltinMethod Function
hi def link salamModuleName    Identifier
hi def link salamLayoutElement Identifier
hi def link salamComment       Comment
hi def link salamBlockComment  Comment
hi def link salamTodo          Todo
hi def link salamDirective     PreProc
hi def link salamDirectiveKey  Special
hi def link salamDirectiveSep  Delimiter
hi def link salamAnnotation    PreProc
hi def link salamString        String
hi def link salamTripleString  String
hi def link salamRawString     String
hi def link salamCharacter     Character
hi def link salamEscape        SpecialChar
hi def link salamEscapeError   Error
hi def link salamNumber        Number
hi def link salamFloat         Float
hi def link salamOperator      Operator
hi def link salamOperatorWord  Operator
hi def link salamDelimiter     Delimiter

let b:current_syntax = 'salam'

let &cpo = s:cpo_save
unlet s:cpo_save
