#!/usr/bin/env python3
"""Turns run.sh's results.json into the markdown tables that go in BENCHMARK.md.

    report.py /tmp/httpbench/results.json [--label after]

One JSON object per line, each one route measured against one server. Missing
cells stay blank rather than zero: a server that was not measured on a route
and a server that scored nothing are different facts.
"""

import json
import sys
from collections import OrderedDict

SERVER_ORDER = ["salam", "nginx", "node", "php"]
SERVER_LABEL = {
    "salam": "Salam",
    "nginx": "nginx",
    "node": "node/express",
    "php": "php -S",
}
ROUTE_LABEL = OrderedDict(
    [
        ("plaintext", "/plaintext"),
        ("json", "/json"),
        ("cached", "/cached"),
        ("file", "/file"),
        ("users", "/users/42"),
        ("search", "/search?q=&n=5"),
        ("compute", "/compute?n=1000"),
        ("headers", "/headers"),
        ("static", "/static/style.css"),
        ("home", "/"),
        ("echo", "POST /echo"),
    ]
)


def load(path):
    rows = {}
    meta = {}
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            r = json.loads(line)
            rows[(r["server"], r["route"])] = r
            meta.setdefault("connections", r.get("connections"))
            meta.setdefault("threads", r.get("threads"))
            meta.setdefault("duration_s", r.get("duration_s"))
    return rows, meta


def fmt_rps(v):
    if v is None:
        return ""
    return f"{v:,.0f}"


def fmt_us(v):
    if v is None:
        return ""
    if v >= 1000:
        return f"{v / 1000:.1f} ms"
    return f"{v:.0f} us"


def table(rows, servers, field, fmt):
    head = "| Route | " + " | ".join(SERVER_LABEL[s] for s in servers) + " |"
    sep = "| --- | " + " | ".join("---:" for _ in servers) + " |"
    out = [head, sep]
    for route, label in ROUTE_LABEL.items():
        cells = []
        for s in servers:
            r = rows.get((s, route))
            cells.append(fmt(r[field]) if r else "")
        if any(cells):
            out.append(f"| `{label}` | " + " | ".join(cells) + " |")
    return "\n".join(out)


def health_table(rows, servers):
    out = [
        "| Server | Route | non-2xx | connect errors | I/O errors | reconnects | died |",
        "| --- | --- | ---: | ---: | ---: | ---: | :---: |",
    ]
    for s in servers:
        for route in ROUTE_LABEL:
            r = rows.get((s, route))
            if not r:
                continue
            bad = r["non2xx"] + r["connect_err"] + r["io_err"]
            if bad == 0 and r["reconnects"] == 0 and not r.get("died"):
                continue
            out.append(
                f"| {SERVER_LABEL[s]} | `{ROUTE_LABEL[route]}` | {r['non2xx']:,} | "
                f"{r['connect_err']:,} | {r['io_err']:,} | {r['reconnects']:,} | "
                f"{'**yes**' if r.get('died') else ''} |"
            )
    return (
        "\n".join(out)
        if len(out) > 2
        else "_No errors, no forced reconnects, no crashes._"
    )


def main():
    path = sys.argv[1]
    rows, meta = load(path)
    servers = [s for s in SERVER_ORDER if any(k[0] == s for k in rows)]
    if not servers:
        print("no results")
        return

    print(f"<!-- generated by bench/report.py from {path} -->")
    print()
    print(
        f"Load: {meta['connections']} connections, {meta['threads']} generator threads, "
        f"{meta['duration_s']:.0f}s measured per route."
    )
    print()
    print("### Requests per second")
    print()
    print(table(rows, servers, "rps", fmt_rps))
    print()
    print("### Requests per minute")
    print()
    print(table(rows, servers, "rpm", fmt_rps))
    print()
    print("### Latency, 99th percentile")
    print()
    print(table(rows, servers, "p99_us", fmt_us))
    print()
    print("### Latency, median")
    print()
    print(table(rows, servers, "p50_us", fmt_us))
    print()
    print("### Errors and forced reconnects")
    print()
    print(health_table(rows, servers))


if __name__ == "__main__":
    main()
