;;; salam-mode.el --- Major mode for the Salam programming language -*- lexical-binding: t; -*-

;; Author: The Salam Team
;; URL: https://github.com/SalamLang/Salam
;; Version: 0.4.4
;; Package-Requires: ((emacs "26.1"))
;; Keywords: languages salam
;; SPDX-License-Identifier: MIT

;;; Commentary:

;; Generated by extensions/tools/gen_syntaxes.salam

;;; Code:

(defvar compilation-error-regexp-alist)
(defvar compilation-error-regexp-alist-alist)
(defvar yas-snippet-dirs)

(defgroup salam nil
  "Support for the Salam programming language."
  :group 'languages
  :prefix "salam-")

(defcustom salam-compiler "salam"
  "Path to the Salam compiler.  A bare name is looked up on ‘exec-path’."
  :type 'string
  :group 'salam)

(defcustom salam-lang "auto"
  "Keyword pack passed to the compiler as --lang.
\"auto\" reads a //! lang: directive, then falls back to detecting the
script the buffer is written in."
  :type '(choice (const "auto") (const "en") (const "fa"))
  :group 'salam)

(defcustom salam-indent-offset 4
  "Number of columns one level of indentation adds."
  :type 'integer
  :group 'salam)

(defcustom salam-format-indent "4"
  "Indentation handed to ‘salam format --indent’: \"tab\", or 1 to 16."
  :type 'string
  :group 'salam)

(defcustom salam-format-on-save nil
  "Reformat the buffer with ‘salam format’ before every save."
  :type 'boolean
  :group 'salam)

(defcustom salam-stdlib-path ""
  "Root directory for std/... imports, passed as --stdlib-path.
An empty string lets the compiler find it."
  :type 'string
  :group 'salam)

(defcustom salam-run-command "exec"
  "Subcommand ‘salam-run’ uses.
\"exec\" is the tree-walking interpreter and needs no C toolchain."
  :type '(choice (const "exec") (const "run"))
  :group 'salam)

(defconst salam-conditional-keywords '("if" "else" "match" "switch" "اگر" "وگرنه" "همخوان" "ترابرد"))
(defconst salam-loop-keywords '("until" "repeat" "each" "تا" "تکرار" "هر"))
(defconst salam-statement-keywords '("ret" "end" "break" "continue" "defer" "to" "by" "in" "with" "برگشت" "پایان" "بشکن" "گذر" "دیرکن" "تا" "از"))
(defconst salam-storage-keywords '("mut" "const" "extern" "pub" "inline" "noinline" "pure" "noret" "deprecated" "ناپایا" "پایا" "فراخوانه" "همگانی" "درخط" "نادرخط" "ناب" "نابرگشت" "بی‌کاره"))
(defconst salam-other-keywords '("on" "as" "layout" "operator" "impl" "بر" "برگردان" "چیدمان" "کارور" "کاربست"))
(defconst salam-function-keywords '("func" "روال"))
(defconst salam-structure-keywords '("type" "struct" "enum" "interface" "component" "گونه" "ساختار" "جداشمار" "میانجی" "بخش"))
(defconst salam-include-keywords '("import" "package" "واردسازی" "بسته"))
(defconst salam-boolean-keywords '("true" "false" "درست" "نادرست"))
(defconst salam-null-keywords '("null" "پوچ"))
(defconst salam-this-keywords '("this" "این"))
(defconst salam-type-keywords '("void" "bool" "char" "str" "uchar" "i8" "i16" "i32" "int" "i64" "u8" "u16" "u32" "uint" "u64" "size" "f32" "float" "f64" "تهی" "منطقی" "نویسه" "رشته" "یونیکد" "صحیح۸" "صحیح۱۶" "صحیح۳۲" "صحیح" "صحیح۶۴" "صحیح8" "صحیح16" "صحیح32" "صحیح64" "طبیعی۸" "طبیعی۱۶" "طبیعی۳۲" "طبیعی" "طبیعی۶۴" "طبیعی8" "طبیعی16" "طبیعی32" "طبیعی64" "اندازه" "اعشار۳۲" "اعشار" "اعشار۶۴" "اعشار32" "اعشار64"))
(defconst salam-auto-keywords '("auto" "خودکار" "تلقائي"))
(defconst salam-builtin-type-keywords '("وکتور" "Vector" "نگاشت" "HashMap" "پیمایشگرنگاشت" "MapIter" "پرونده" "File" "گوناگون" "Variant"))
(defconst salam-builtin-keywords '("print" "println" "printerr" "printerrln" "input" "چاپ" "سرچاپ" "نادرست‌چاپ" "نادرست‌سرچاپ" "ورودی"))
(defconst salam-word-operators '("و" "یا" "برابر" "نابرابر"))
(defconst salam-contextual-keywords '("link" "static" "dynamic" "framework" "پیوند" "ایستا" "پویا" "چارچوب" "dyn"))
(defconst salam-directive-keywords '("mode" "title" "lang" "dir" "name" "version"))
(defconst salam-builtin-methods '("بیفزا" "push" "دربیاور" "pop" "بگیر" "get" "ارجاع" "ref" "بنشان" "set" "طول" "len" "ظرفیت" "cap" "آزادکن" "free" "درج" "put" "دارد" "has" "حذف" "remove" "اندازه" "size" "پیمایش" "iter" "داردبعدی" "has_next" "کلید" "key" "مقدار" "value" "بعدی" "next" "خواندن" "read" "خواندن خط" "readline" "نوشتن" "write" "جابجایی" "seek" "ببند" "close" "پیوست" "concat" "زیررشته" "substr" "بیاب" "find" "بشکاف" "split" "پیراست" "trim" "به صحیح" "to_int" "به اعشار" "to_float"))
(defconst salam-end-keywords '("end" "پایان"))
(defconst salam-else-keywords '("else" "وگرنه"))
(defconst salam-all-keywords '("ret" "if" "else" "until" "end" "break" "continue" "defer" "repeat" "to" "by" "each" "in" "with" "match" "switch" "برگشت" "اگر" "وگرنه" "تا" "پایان" "بشکن" "گذر" "دیرکن" "تکرار" "هر" "از" "همخوان" "ترابرد" "func" "on" "mut" "const" "type" "struct" "enum" "import" "as" "layout" "package" "operator" "extern" "interface" "pub" "inline" "noinline" "pure" "noret" "deprecated" "component" "impl" "روال" "بر" "ناپایا" "پایا" "گونه" "ساختار" "جداشمار" "واردسازی" "برگردان" "چیدمان" "بسته" "کارور" "فراخوانه" "میانجی" "همگانی" "درخط" "نادرخط" "ناب" "نابرگشت" "بی‌کاره" "بخش" "کاربست" "true" "false" "null" "درست" "نادرست" "پوچ" "this" "این" "print" "println" "printerr" "printerrln" "input" "چاپ" "سرچاپ" "نادرست‌چاپ" "نادرست‌سرچاپ" "ورودی" "و" "یا" "برابر" "نابرابر"))

(defconst salam--ident-chars "[[:alnum:]_؀-ۿݐ-ݿࢠ-ࣿﭐ-﷿ﹰ-﻿‌‍]"
  "Character class matching one identifier character, Arabic script included.")

(defconst salam--ident (concat "[[:alpha:]_؀-ۿݐ-ݿࢠ-ࣿﭐ-﷿ﹰ-﻿‌‍]" salam--ident-chars "*")
  "Regexp matching a whole identifier.")

(defconst salam--digit "[0-9٠-٩۰-۹]"
  "Character class matching one digit, Persian and Arabic-Indic included.")

(defun salam--words (words)
  "Return a regexp matching any of WORDS as a whole word."
  (concat "\\<" (regexp-opt words) "\\>"))

(defvar salam-mode-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?/ ". 124" table)
    (modify-syntax-entry ?* ". 23b" table)
    (modify-syntax-entry ?\n ">" table)
    (modify-syntax-entry ?\" "\"" table)
    (modify-syntax-entry ?\\ "\\" table)
    (modify-syntax-entry ?` "\"" table)
    (modify-syntax-entry ?' "." table)
    (modify-syntax-entry ?_ "w" table)
    (modify-syntax-entry ?@ "." table)
    (modify-syntax-entry '(?\u0600 . ?\u06ff) "w" table)
    (modify-syntax-entry '(?\u0750 . ?\u077f) "w" table)
    (modify-syntax-entry '(?\u08a0 . ?\u08ff) "w" table)
    (modify-syntax-entry '(?\ufb50 . ?\ufdff) "w" table)
    (modify-syntax-entry '(?\ufe70 . ?\ufeff) "w" table)
    (modify-syntax-entry ?\u200c "w" table)
    (modify-syntax-entry ?\u200d "w" table)
    table)
  "Syntax table for ‘salam-mode’.")

(defun salam--propertize (start end)
  "Mark every \"\"\" between START and END as a generic string fence.
Without this the first two quotes of \"\"\" read as an empty string and the
third opens one, which would mis-colour the rest of the buffer."
  (goto-char start)
  (while (search-forward "\"\"\"" end t)
    (let ((open (- (point) 3)))
      (put-text-property open (1+ open) 'syntax-table (string-to-syntax "|"))
      (put-text-property (1+ open) (point) 'syntax-table (string-to-syntax ".")))))

(defvar salam-font-lock-keywords
  (list
   (list (concat "^\\s-*\\(//!\\)\\(.*\\)$")
         '(1 font-lock-preprocessor-face t)
         '(2 font-lock-preprocessor-face t))
   (list (concat "\\(" (salam--words salam-function-keywords) "\\)\\s-+\\(" salam--ident "\\)")
         '(1 font-lock-keyword-face)
         '(2 font-lock-function-name-face))
   (list (concat "\\(" (salam--words salam-structure-keywords) "\\)\\s-+\\(" salam--ident "\\)")
         '(1 font-lock-keyword-face)
         '(2 font-lock-type-face))
   (list (concat "\\(" (salam--words salam-include-keywords) "\\)\\s-+\\([^ \t\n]+\\)")
         '(1 font-lock-keyword-face)
         '(2 font-lock-constant-face))
   (cons "@[A-Za-z_][A-Za-z0-9_]*" 'font-lock-preprocessor-face)
   (cons (salam--words salam-conditional-keywords) 'font-lock-keyword-face)
   (cons (salam--words salam-loop-keywords) 'font-lock-keyword-face)
   (cons (salam--words salam-statement-keywords) 'font-lock-keyword-face)
   (cons (salam--words salam-storage-keywords) 'font-lock-keyword-face)
   (cons (salam--words salam-other-keywords) 'font-lock-keyword-face)
   (cons (salam--words salam-contextual-keywords) 'font-lock-keyword-face)
   (cons (salam--words salam-word-operators) 'font-lock-keyword-face)
   (cons (salam--words salam-boolean-keywords) 'font-lock-constant-face)
   (cons (salam--words salam-null-keywords) 'font-lock-constant-face)
   (cons (salam--words salam-this-keywords) 'font-lock-builtin-face)
   (cons (salam--words salam-type-keywords) 'font-lock-type-face)
   (cons (salam--words salam-auto-keywords) 'font-lock-type-face)
   (cons (salam--words salam-builtin-type-keywords) 'font-lock-type-face)
   (cons (salam--words salam-builtin-keywords) 'font-lock-builtin-face)
   (cons (concat "\\.\\(" (regexp-opt salam-builtin-methods) "\\)\\>") '(1 font-lock-builtin-face))
   (cons (concat "\\(" salam--ident "\\)\\s-*(") '(1 font-lock-function-name-face))
   (cons (concat "\\<" salam--digit "[" "0-9٠-٩۰-۹" "_]*\\(\\." salam--digit "[0-9٠-٩۰-۹_]*\\)?\\(?:[eE][+-]?" salam--digit "+\\)?f?\\>")
         'font-lock-constant-face)
   (cons "\\<0[xX][0-9A-Fa-f][0-9A-Fa-f_]*\\>" 'font-lock-constant-face)
   (cons "\\<0[bB][01][01_]*\\>" 'font-lock-constant-face)
   (cons "\\<0[oO][0-7][0-7_]*\\>" 'font-lock-constant-face)
   (cons "u?'\\(?:\\\\.\\|[^'\\\\]\\)'" 'font-lock-string-face))
  "Font lock rules for ‘salam-mode’.")

(defun salam--line-code (&optional position)
  "Return the current line with strings and comments blanked out.
With POSITION, use the line holding that buffer position."
  (save-excursion
    (when position (goto-char position))
    (let ((line (buffer-substring-no-properties
                 (line-beginning-position) (line-end-position))))
      (setq line (replace-regexp-in-string "\"\"\".*?\"\"\"" "\"\"" line))
      (setq line (replace-regexp-in-string "\"\\(?:\\\\.\\|[^\"\\\\]\\)*\"" "\"\"" line))
      (setq line (replace-regexp-in-string "'\\(?:\\\\.\\|[^'\\\\]\\)*'" "''" line))
      (setq line (replace-regexp-in-string "//.*$" "" line))
      (string-trim-right line))))

(defun salam--previous-code-line ()
  "Move point to the closest line above that carries code.
Return nil when there is none."
  (let ((found nil))
    (while (and (not found) (zerop (forward-line -1)))
      (unless (string-match-p "\\`[ \t]*\\'" (salam--line-code))
        (setq found t)))
    found))

(defun salam-indent-line ()
  "Indent the current line according to the block structure."
  (interactive)
  (let* ((opens-block "[ \t]*:[ \t]*\\'")
         (closes (concat "\\`[ \t]*" (regexp-opt salam-end-keywords) "[ \t]*\\'"))
         (dedents (concat "\\`[ \t]*" (regexp-opt salam-else-keywords) "\\(?:[ \t]\\|:\\)"))
         (current (salam--line-code))
         (target
          (save-excursion
            (if (not (salam--previous-code-line))
                0
              (let ((indent (current-indentation))
                    (previous (salam--line-code)))
                (when (string-match-p opens-block previous)
                  (setq indent (+ indent salam-indent-offset)))
                indent)))))
    (when (or (string-match-p closes current) (string-match-p dedents current))
      (setq target (- target salam-indent-offset)))
    (indent-line-to (max target 0))))

(defun salam--detect-lang ()
  "Return the keyword pack this buffer is written in: \"en\" or \"fa\"."
  (if (member salam-lang '("en" "fa"))
      salam-lang
    (save-excursion
      (goto-char (point-min))
      (let ((head (buffer-substring-no-properties
                   (point-min) (min (point-max) (+ (point-min) 4000)))))
        (cond
         ((string-match "\\(?:lang\\|LANG\\|\u0632\u0628\u0627\u0646\\)[ \t]*:[ \t]*\\([A-Za-z][A-Za-z]\\)" head)
          (downcase (match-string 1 head)))
         ((>= (length (replace-regexp-in-string "[^\u0600-\u06ff\ufb50-\ufeff]" "" head)) 3) "fa")
         (t "en"))))))

(defun salam--common-args ()
  "Return the compiler options every invocation carries."
  (append (list (concat "--lang=" (salam--detect-lang)))
          (unless (string-empty-p salam-stdlib-path)
            (list (concat "--stdlib-path=" salam-stdlib-path)))))

(defun salam--null-device ()
  "Return the platform's bit bucket."
  (if (memq system-type '(windows-nt ms-dos)) "NUL" "/dev/null"))

(defun salam--compile (args)
  "Run the compiler with ARGS through ‘compile’."
  (let ((compile-command
         (mapconcat #'shell-quote-argument (cons salam-compiler args) " ")))
    (compile compile-command)))

(defun salam--current-file ()
  "Return the buffer's file, saving it first so the compiler reads this text.
Signals when the buffer has never been written, which would otherwise build a
command line containing nil."
  (unless (buffer-file-name)
    (user-error "This buffer has no file; save it before running the compiler"))
  (when (buffer-modified-p)
    (save-buffer))
  (buffer-file-name))

(defun salam-run ()
  "Run the current buffer's file."
  (interactive)
  (salam--compile (append (list salam-run-command (salam--current-file) "--error-style=gcc")
                          (salam--common-args))))

(defun salam-build ()
  "Compile the current buffer's file to an executable."
  (interactive)
  (salam--compile (append (list "build" (salam--current-file) "--error-style=gcc")
                          (salam--common-args))))

(defun salam-check ()
  "Type-check the current buffer's file without running it."
  (interactive)
  (salam--compile (append (list "inspect" (salam--current-file)
                                "--emit-symbol"
                                (concat "--xml-out=" (salam--null-device))
                                "--error-style=gcc"
                                "--log-level=error")
                          (salam--common-args))))

(defun salam-format-buffer ()
  "Reformat the buffer with ‘salam format’, keeping point where it is."
  (interactive)
  (let* ((temporary (make-temp-file "salam-fmt-" nil ".salam"))
         (original (buffer-substring-no-properties (point-min) (point-max)))
         (arguments (append (list "format" temporary
                                  (concat "--indent=" salam-format-indent)
                                  "--error-style=gcc")
                            (salam--common-args))))
    (unwind-protect
        (progn
          (let ((coding-system-for-write 'utf-8-unix))
            (write-region original nil temporary nil 'quiet))
          (with-temp-buffer
            (let ((status (apply #'call-process salam-compiler nil t nil arguments)))
              (unless (eq status 0)
                (error "salam format failed: %s" (string-trim (buffer-string))))))
          (let ((formatted (with-temp-buffer
                             (insert-file-contents temporary)
                             (buffer-string))))
            (unless (string= formatted original)
              (let ((line (line-number-at-pos))
                    (column (current-column)))
                (erase-buffer)
                (insert formatted)
                (goto-char (point-min))
                (forward-line (1- line))
                (move-to-column column)))))
      (delete-file temporary))))

(defun salam--format-on-save ()
  "Reformat before saving when ‘salam-format-on-save’ is non-nil."
  (when salam-format-on-save
    (salam-format-buffer)))

(defvar salam-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c C-r") #'salam-run)
    (define-key map (kbd "C-c C-b") #'salam-build)
    (define-key map (kbd "C-c C-c") #'salam-check)
    (define-key map (kbd "C-c C-f") #'salam-format-buffer)
    map)
  "Keymap for ‘salam-mode’.")

(defconst salam--imenu-expression
  (list (list "Function"
              (concat "^[ \t]*\\(?:\\w+[ \t]+\\)*" (salam--words salam-function-keywords)
                      "[ \t]+\\(" salam--ident "\\)")
              1)
        (list "Type"
              (concat "^[ \t]*\\(?:\\w+[ \t]+\\)*" (salam--words salam-structure-keywords)
                      "[ \t]+\\(" salam--ident "\\)")
              1))
  "Imenu patterns for ‘salam-mode’.")

(define-derived-mode salam-mode prog-mode "Salam"
  "Major mode for editing Salam source code.

\\{salam-mode-map}"
  :syntax-table salam-mode-syntax-table
  (setq-local font-lock-defaults '(salam-font-lock-keywords))
  (setq-local syntax-propertize-function #'salam--propertize)
  (setq-local comment-start "// ")
  (setq-local comment-end "")
  (setq-local comment-start-skip "\\(?://+\\|/\\*+\\)\\s *")
  (setq-local indent-line-function #'salam-indent-line)
  (setq-local indent-tabs-mode nil)
  (setq-local tab-width salam-indent-offset)
  (setq-local electric-indent-chars (append electric-indent-chars '(?:)))
  (setq-local imenu-generic-expression salam--imenu-expression)
  (setq-local require-final-newline t)
  (setq-local bidi-paragraph-direction 'left-to-right)
  (add-hook 'before-save-hook #'salam--format-on-save nil t))

(add-to-list 'auto-mode-alist '("\\.salam\\'" . salam-mode))

(with-eval-after-load 'compile
  (add-to-list 'compilation-error-regexp-alist-alist
               '(salam "^\\(.+?\\):\\([0-9]+\\):\\([0-9]+\\): \\(?:\\(error\\)\\|\\(warning\\)\\|note\\): "
                       1 2 3 (5 . 4)))
  (add-to-list 'compilation-error-regexp-alist 'salam))

(with-eval-after-load 'yasnippet
  (let ((directory (expand-file-name
                    "snippets"
                    (file-name-directory (or load-file-name buffer-file-name "")))))
    (when (file-directory-p directory)
      (add-to-list 'yas-snippet-dirs directory t))))

(provide 'salam-mode)

;;; salam-mode.el ends here
