---
failure-threshold: info
ignored:
  - DL3008 # Pin versions in apt-get install: https://github.com/hadolint/hadolint/wiki/DL3008
  - DL3018 # Pin versions in apk add: https://github.com/hadolint/hadolint/wiki/DL3018
  - DL4006 # Set the SHELL option -o pipefail before RUN with a pipe in: https://github.com/hadolint/hadolint/wiki/DL4006
