# MD013/line-length Line length
MD013: false

# MD026/no-trailing-punctuation Trailing punctuation in heading
MD026: false

# MD040/fenced-code-language Fenced code blocks should have a language specified
MD040: false
