# https://yamllint.readthedocs.io/en/stable/
extends: default
rules:
  braces:
    min-spaces-inside: 1
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  document-start: disable
  line-length: disable
  truthy: false
