export enum ValidatorMessageKeys {
    VALIDATOR_PREFIX = 'VALIDATOR_PREFIX',
    VALIDATOR_ATTRIBUTE_REQUIRED = 'VALIDATOR_ATTRIBUTE_REQUIRED',
    VALIDATOR_ELEMENT_NOT_VALID = 'VALIDATOR_ELEMENT_NOT_VALID',
    VALIDATOR_ELEMENT_STYLE_STATE_NOT_VALID = 'VALIDATOR_ELEMENT_STYLE_STATE_NOT_VALID',
    VALIDATOR_ELEMENT_OR_STYLE_STATE_NOT_VALID = 'VALIDATOR_ELEMENT_OR_STYLE_STATE_NOT_VALID',
    VALIDATOR_ATTRIBUTE_RESERVED_VALUE_NOT_VALID = 'VALIDATOR_ATTRIBUTE_RESERVED_VALUE_NOT_VALID',
    VALIDATOR_ATTRIBUTE_NOT_VALID = 'VALIDATOR_ATTRIBUTE_NOT_VALID',
    VALIDATOR_STYLE_ATTRIBUTE_NOT_VALID = 'VALIDATOR_STYLE_ATTRIBUTE_NOT_VALID',
    VALIDATOR_ATTRIBUTE_VALUE_NOT_VALID = 'VALIDATOR_ATTRIBUTE_VALUE_NOT_VALID',
    VALIDATOR_ATTRIBUTE_VALUE_NOT_EMPTY = 'VALIDATOR_ATTRIBUTE_VALUE_NOT_EMPTY',
    VALIDATOR_ATTRIBUTE_NOT_SUPPORTED = 'VALIDATOR_ATTRIBUTE_NOT_SUPPORTED',
    VALIDATOR_SAVE_OUTPUT_ERROR = 'VALIDATOR_SAVE_OUTPUT_ERROR',
};
