export enum GeneratorMessageKeys {
    GENERATOR_PREFIX = 'GENERATOR_PREFIX',
    GENERATOR_CANNOT_OUTDENT_BELOW_ZERO = 'GENERATOR_CANNOT_OUTDENT_BELOW_ZERO',
    GENERATOR_UNKNOWN_ELEMENT_TYPE = 'GENERATOR_UNKNOWN_ELEMENT_TYPE',
    GENERATOR_INCLUDE_FILE_PATH_NOT_PROVIDED = 'GENERATOR_INCLUDE_FILE_PATH_NOT_PROVIDED',
    GENERATOR_INCLUDE_FILE_NOT_FOUND = 'GENERATOR_INCLUDE_FILE_NOT_FOUND',
    GENERATOR_INCLUDE_FILE_READ_ERROR = 'GENERATOR_INCLUDE_FILE_READ_ERROR',
    GENERATOR_INCLUDE_HTTP_ERROR_HTTP_STATUS = 'GENERATOR_INCLUDE_HTTP_ERROR_HTTP_STATUS',
    GENERATOR_INCLUDE_HTTP_ERROR = 'GENERATOR_INCLUDE_HTTP_ERROR',
    GENERATOR_SAVE_OUTPUT_ERROR = 'GENERATOR_SAVE_OUTPUT_ERROR',
};
