#ifndef _STAGE_AST_ASTS_AST_PARAMETER_AST_PARAMETERS_AST_PARAMETERS_CREATE_AST_PARAMETERS_CREATE_H_
#define _STAGE_AST_ASTS_AST_PARAMETER_AST_PARAMETERS_AST_PARAMETERS_CREATE_AST_PARAMETERS_CREATE_H_

#include <stddef.h> // for size_t

// base
#include <base.h>

// ast
#include <stage/ast/type.h>

#endif // _STAGE_AST_ASTS_AST_PARAMETER_AST_PARAMETERS_AST_PARAMETERS_CREATE_AST_PARAMETERS_CREATE_H_
