/*
 * Salam Programming Language (2024-2026)
 *
 *   +-------------------+
 *   |     S A L A M     |
 *   +-------------------+
 *
 * Designed by Seyyed Ali Mohammadiyeh and the Salam Team
 * Born from a decade of language design experience (since 2018)
 *
 * Repository: https://github.com/SalamLang/Salam
 *
 */

/*
 * Static HTML assets for `salam doc`: the inline stylesheet, the inline viewer
 * script, and the body skeleton that script renders into. Byte-for-byte the
 * same assets the self-hosted compiler/docgen.salam carries as backtick
 * raw-string literals - the two must stay in sync.
 *
 * GENERATED FILE - do not hand-edit. Regenerate after changing the assets in
 * compiler/docgen.salam with:
 *
 *     python c/tools/python/gen_doc_assets.py
 *
 * One C string literal per source line, rather than one huge concatenated
 * literal, keeps every literal well inside C90's guaranteed 509-character
 * limit and keeps the diff against the .salam original line-addressable.
 */

#include "core/prelude.h"
#include "doc/docgen.h"

const char *const doc_css_lines[] = {
    "\n",
    ":root {\n",
    "  --bg: #ffffff;\n",
    "  --bg-alt: #f6f7f9;\n",
    "  --fg: #1a1d23;\n",
    "  --fg-muted: #5b6270;\n",
    "  --border: #e3e6ea;\n",
    "  --accent: #3860ff;\n",
    "  --accent-fg: #ffffff;\n",
    "  --code-bg: #f0f2f5;\n",
    "  --badge-priv-bg: #fdecec;\n",
    "  --badge-priv-fg: #b3261e;\n",
    "  --badge-dep-bg: #fff4e0;\n",
    "  --badge-dep-fg: #9a5b00;\n",
    "  --shadow: 0 1px 3px rgba(20, 22, 30, 0.08);\n",
    "  color-scheme: light;\n",
    "}\n",
    "@media (prefers-color-scheme: dark) {\n",
    "  :root:not([data-theme=\"light\"]) {\n",
    "    --bg: #14161c;\n",
    "    --bg-alt: #1b1e26;\n",
    "    --fg: #e7e9ee;\n",
    "    --fg-muted: #9aa1b1;\n",
    "    --border: #2a2e39;\n",
    "    --accent: #7b9bff;\n",
    "    --accent-fg: #10131a;\n",
    "    --code-bg: #10131a;\n",
    "    --badge-priv-bg: #3a1c1c;\n",
    "    --badge-priv-fg: #ff9d92;\n",
    "    --badge-dep-bg: #3a2c10;\n",
    "    --badge-dep-fg: #ffcb7a;\n",
    "    --shadow: 0 1px 3px rgba(0, 0, 0, 0.4);\n",
    "    color-scheme: dark;\n",
    "  }\n",
    "}\n",
    ":root[data-theme=\"dark\"] {\n",
    "  --bg: #14161c;\n",
    "  --bg-alt: #1b1e26;\n",
    "  --fg: #e7e9ee;\n",
    "  --fg-muted: #9aa1b1;\n",
    "  --border: #2a2e39;\n",
    "  --accent: #7b9bff;\n",
    "  --accent-fg: #10131a;\n",
    "  --code-bg: #10131a;\n",
    "  --badge-priv-bg: #3a1c1c;\n",
    "  --badge-priv-fg: #ff9d92;\n",
    "  --badge-dep-bg: #3a2c10;\n",
    "  --badge-dep-fg: #ffcb7a;\n",
    "  --shadow: 0 1px 3px rgba(0, 0, 0, 0.4);\n",
    "  color-scheme: dark;\n",
    "}\n",
    "* { box-sizing: border-box; }\n",
    "html, body { margin: 0; padding: 0; }\n",
    "body {\n",
    "  background: var(--bg);\n",
    "  color: var(--fg);\n",
    "  font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif;\n",
    "  font-size: 15px;\n",
    "  line-height: 1.55;\n",
    "}\n",
    "code, pre, .mono { font-family: ui-monospace, SFMono-Regular, Consolas, \"Liberation Mono\", Menlo, monospace; }\n",
    "a { color: var(--accent); text-decoration: none; }\n",
    "a:hover { text-decoration: underline; }\n",
    ".topbar {\n",
    "  position: sticky; top: 0; z-index: 20;\n",
    "  display: flex; align-items: center; gap: 12px;\n",
    "  padding: 10px 16px;\n",
    "  background: var(--bg); border-bottom: 1px solid var(--border);\n",
    "}\n",
    ".topbar .title { font-weight: 600; font-size: 15px; white-space: nowrap; margin-right: 4px; }\n",
    ".topbar input[type=\"search\"] {\n",
    "  flex: 1 1 220px; min-width: 120px; max-width: 420px;\n",
    "  padding: 7px 10px; border-radius: 8px; border: 1px solid var(--border);\n",
    "  background: var(--bg-alt); color: var(--fg); font-size: 14px;\n",
    "}\n",
    ".topbar label { display: flex; align-items: center; gap: 6px; font-size: 13px; color: var(--fg-muted); white-space: nowrap; }\n",
    ".topbar select {\n",
    "  padding: 6px 8px; border-radius: 8px; border: 1px solid var(--border);\n",
    "  background: var(--bg-alt); color: var(--fg); font-size: 13px;\n",
    "}\n",
    ".icon-btn {\n",
    "  border: 1px solid var(--border); background: var(--bg-alt); color: var(--fg);\n",
    "  border-radius: 8px; padding: 6px 10px; font-size: 13px; cursor: pointer;\n",
    "}\n",
    ".icon-btn:hover { border-color: var(--accent); }\n",
    "#sidebar-toggle { display: none; }\n",
    ".layout { display: flex; align-items: flex-start; }\n",
    "aside.sidebar {\n",
    "  width: 280px; flex: 0 0 280px; position: sticky; top: 49px;\n",
    "  height: calc(100vh - 49px); overflow-y: auto;\n",
    "  border-right: 1px solid var(--border); background: var(--bg-alt);\n",
    "  padding: 10px 0;\n",
    "}\n",
    ".nav-file {\n",
    "  padding: 10px 14px 4px; font-size: 11px; font-weight: 700; letter-spacing: 0.03em;\n",
    "  text-transform: uppercase; color: var(--fg-muted);\n",
    "}\n",
    ".nav-item {\n",
    "  display: flex; align-items: center; gap: 8px;\n",
    "  padding: 5px 14px; font-size: 13px; color: var(--fg);\n",
    "}\n",
    ".nav-item:hover { background: var(--border); text-decoration: none; }\n",
    ".nav-kind {\n",
    "  display: inline-flex; align-items: center; justify-content: center;\n",
    "  width: 18px; height: 18px; border-radius: 5px; font-size: 10px; font-weight: 700;\n",
    "  background: var(--accent); color: var(--accent-fg); flex: none;\n",
    "}\n",
    ".nav-name { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }\n",
    ".nav-lock { margin-left: auto; font-size: 10px; color: var(--fg-muted); flex: none; }\n",
    "main#main-content { flex: 1 1 auto; min-width: 0; padding: 20px 28px 80px; max-width: 920px; }\n",
    ".file-heading {\n",
    "  font-size: 13px; font-weight: 700; color: var(--fg-muted);\n",
    "  margin: 32px 0 10px; padding-bottom: 6px; border-bottom: 1px solid var(--border);\n",
    "}\n",
    ".file-heading:first-child { margin-top: 0; }\n",
    ".empty-state { color: var(--fg-muted); padding: 40px 0; text-align: center; }\n",
    ".decl-card {\n",
    "  background: var(--bg); border: 1px solid var(--border); border-radius: 10px;\n",
    "  padding: 16px 18px; margin-bottom: 14px; box-shadow: var(--shadow);\n",
    "}\n",
    ".decl-head { display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; }\n",
    ".decl-name { margin: 0; font-size: 16px; font-weight: 650; }\n",
    ".decl-source-name { font-size: 12px; color: var(--fg-muted); font-family: ui-monospace, monospace; }\n",
    ".kind-tag {\n",
    "  font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.03em;\n",
    "  padding: 2px 7px; border-radius: 5px; background: var(--accent); color: var(--accent-fg);\n",
    "}\n",
    ".badge { font-size: 10px; font-weight: 700; text-transform: uppercase; padding: 2px 7px; border-radius: 5px; }\n",
    ".badge-private { background: var(--badge-priv-bg); color: var(--badge-priv-fg); }\n",
    ".badge-dep { background: var(--badge-dep-bg); color: var(--badge-dep-fg); }\n",
    ".decl-sig, .member-sig {\n",
    "  background: var(--code-bg); border-radius: 8px; padding: 10px 12px; margin: 10px 0 0;\n",
    "  font-size: 13px; overflow-x: auto; white-space: pre;\n",
    "}\n",
    ".decl-doc, .member-doc { margin: 10px 0 0; color: var(--fg); white-space: pre-wrap; }\n",
    ".member-list { margin-top: 14px; border-top: 1px solid var(--border); padding-top: 10px; }\n",
    ".member-row { padding: 8px 0; border-bottom: 1px dashed var(--border); }\n",
    ".member-row:last-child { border-bottom: none; }\n",
    ".member-head { display: flex; align-items: center; gap: 8px; }\n",
    ".member-name { font-weight: 600; font-size: 13.5px; }\n",
    ".member-sig { font-size: 12.5px; }\n",
    ".member-doc { font-size: 13px; }\n",
    "@media (max-width: 860px) {\n",
    "  aside.sidebar {\n",
    "    position: fixed; left: 0; top: 49px; bottom: 0; z-index: 15;\n",
    "    transform: translateX(-100%); transition: transform 0.15s ease; box-shadow: var(--shadow);\n",
    "  }\n",
    "  body.sidebar-open aside.sidebar { transform: translateX(0); }\n",
    "  #sidebar-toggle { display: inline-flex; }\n",
    "  main#main-content { padding: 16px; }\n",
    "  .topbar .title { display: none; }\n",
    "}\n",
    NULL};

const char *const doc_js_lines[] = {
    "\n",
    "(function () {\n",
    "  \"use strict\";\n",
    "  var state = { lang: \"\", showPrivate: false, query: \"\" };\n",
    "  var KIND_ORDER = { struct: 0, interface: 1, enum: 2, impl: 3, type: 4, const: 5, var: 6, func: 7, field: 8, member: 9 };\n",
    "  var KIND_LABEL = { const: \"Const\", var: \"Var\", type: \"Type\", struct: \"Struct\", interface: \"Interface\", enum: \"Enum\", impl: \"Impl\", func: \"Func\", field: \"Field\", member: \"Member\" };\n",
    "\n",
    "  function el(tag, cls, text) {\n",
    "    var e = document.createElement(tag);\n",
    "    if (cls) e.className = cls;\n",
    "    if (text !== undefined && text !== null && text !== \"\") e.textContent = text;\n",
    "    return e;\n",
    "  }\n",
    "\n",
    "  function pairGet(pairs, lang) {\n",
    "    for (var i = 0; i < pairs.length; i++) {\n",
    "      if (pairs[i][0] === lang) return pairs[i][1];\n",
    "    }\n",
    "    return null;\n",
    "  }\n",
    "\n",
    "  function collectLangs() {\n",
    "    var seen = {};\n",
    "    var out = [];\n",
    "    DOC.decls.forEach(function (d) {\n",
    "      [d.a, d.doc].forEach(function (pairs) {\n",
    "        pairs.forEach(function (pair) {\n",
    "          var lg = pair[0];\n",
    "          if (lg && !seen[lg]) { seen[lg] = true; out.push(lg); }\n",
    "        });\n",
    "      });\n",
    "    });\n",
    "    out.sort();\n",
    "    return out;\n",
    "  }\n",
    "\n",
    "  function displayName(d) {\n",
    "    if (state.lang) {\n",
    "      var v = pairGet(d.a, state.lang);\n",
    "      if (v) return v;\n",
    "    }\n",
    "    var en = pairGet(d.a, \"en\");\n",
    "    if (en) return en;\n",
    "    if (d.a.length >= 1) return d.a[0][1];\n",
    "    return d.n;\n",
    "  }\n",
    "\n",
    "  function displayDoc(d) {\n",
    "    if (state.lang) {\n",
    "      var v = pairGet(d.doc, state.lang);\n",
    "      if (v) return v;\n",
    "    }\n",
    "    var en = pairGet(d.doc, \"en\");\n",
    "    if (en) return en;\n",
    "    if (d.doc.length >= 1) return d.doc[0][1];\n",
    "    return \"\";\n",
    "  }\n",
    "\n",
    "  function matchesQuery(d) {\n",
    "    if (!state.query) return true;\n",
    "    var q = state.query.toLowerCase();\n",
    "    if (d.n.toLowerCase().indexOf(q) !== -1) return true;\n",
    "    if (d.s.toLowerCase().indexOf(q) !== -1) return true;\n",
    "    for (var i = 0; i < d.a.length; i++) {\n",
    "      if (d.a[i][1].toLowerCase().indexOf(q) !== -1) return true;\n",
    "    }\n",
    "    return false;\n",
    "  }\n",
    "\n",
    "  function declVisible(i) {\n",
    "    var d = DOC.decls[i];\n",
    "    if (!state.showPrivate && !d.p) return false;\n",
    "    if (matchesQuery(d)) return true;\n",
    "    for (var mi = 0; mi < d.m.length; mi++) {\n",
    "      var md = DOC.decls[d.m[mi]];\n",
    "      if ((state.showPrivate || md.p) && matchesQuery(md)) return true;\n",
    "    }\n",
    "    return false;\n",
    "  }\n",
    "\n",
    "  function topLevelForFile(fi) {\n",
    "    var out = [];\n",
    "    for (var i = 0; i < DOC.decls.length; i++) {\n",
    "      if (DOC.decls[i].f === fi && DOC.decls[i].par === -1) out.push(i);\n",
    "    }\n",
    "    out.sort(function (ai, bi) {\n",
    "      var a = DOC.decls[ai], b = DOC.decls[bi];\n",
    "      var ka = KIND_ORDER[a.k]; if (ka === undefined) ka = 99;\n",
    "      var kb = KIND_ORDER[b.k]; if (kb === undefined) kb = 99;\n",
    "      if (ka !== kb) return ka - kb;\n",
    "      if (a.p !== b.p) return a.p \? -1 : 1;\n",
    "      return a.n < b.n \? -1 : (a.n > b.n \? 1 : 0);\n",
    "    });\n",
    "    return out;\n",
    "  }\n",
    "\n",
    "  function renderNavItem(container, i) {\n",
    "    var d = DOC.decls[i];\n",
    "    var a = el(\"a\", \"nav-item kind-\" + d.k, null);\n",
    "    a.href = \"#decl-\" + i;\n",
    "    var label = KIND_LABEL[d.k] || d.k;\n",
    "    a.appendChild(el(\"span\", \"nav-kind\", label.substring(0, 1)));\n",
    "    a.appendChild(el(\"span\", \"nav-name\", displayName(d)));\n",
    "    if (!d.p) a.appendChild(el(\"span\", \"nav-lock\", \"private\"));\n",
    "    container.appendChild(a);\n",
    "  }\n",
    "\n",
    "  function sigLine(d) {\n",
    "    return d.s \? d.s : d.n;\n",
    "  }\n",
    "\n",
    "  function renderMemberRow(container, mi) {\n",
    "    var md = DOC.decls[mi];\n",
    "    if (!state.showPrivate && !md.p) return;\n",
    "    if (state.query && !matchesQuery(md)) return;\n",
    "    var row = el(\"div\", \"member-row\", null);\n",
    "    row.id = \"decl-\" + mi;\n",
    "    var head = el(\"div\", \"member-head\", null);\n",
    "    if (!md.p) head.appendChild(el(\"span\", \"badge badge-private\", \"private\"));\n",
    "    if (md.dep) head.appendChild(el(\"span\", \"badge badge-dep\", \"deprecated\"));\n",
    "    head.appendChild(el(\"span\", \"member-name\", displayName(md)));\n",
    "    row.appendChild(head);\n",
    "    var sig = el(\"pre\", \"member-sig\", null);\n",
    "    sig.appendChild(el(\"code\", null, sigLine(md)));\n",
    "    row.appendChild(sig);\n",
    "    var doc = displayDoc(md);\n",
    "    if (doc) row.appendChild(el(\"p\", \"member-doc\", doc));\n",
    "    container.appendChild(row);\n",
    "  }\n",
    "\n",
    "  function renderCard(container, i) {\n",
    "    var d = DOC.decls[i];\n",
    "    var card = el(\"section\", \"decl-card\", null);\n",
    "    card.id = \"decl-\" + i;\n",
    "    var head = el(\"div\", \"decl-head\", null);\n",
    "    head.appendChild(el(\"span\", \"kind-tag\", KIND_LABEL[d.k] || d.k));\n",
    "    if (!d.p) head.appendChild(el(\"span\", \"badge badge-private\", \"private\"));\n",
    "    if (d.dep) head.appendChild(el(\"span\", \"badge badge-dep\", \"deprecated\"));\n",
    "    var dn = displayName(d);\n",
    "    head.appendChild(el(\"h3\", \"decl-name\", dn));\n",
    "    if (dn !== d.n) head.appendChild(el(\"span\", \"decl-source-name\", d.n));\n",
    "    card.appendChild(head);\n",
    "    var sig = el(\"pre\", \"decl-sig\", null);\n",
    "    sig.appendChild(el(\"code\", null, sigLine(d)));\n",
    "    card.appendChild(sig);\n",
    "    var doc = displayDoc(d);\n",
    "    if (doc) card.appendChild(el(\"p\", \"decl-doc\", doc));\n",
    "    if (d.m.length) {\n",
    "      var mlist = el(\"div\", \"member-list\", null);\n",
    "      d.m.forEach(function (mi) { renderMemberRow(mlist, mi); });\n",
    "      if (mlist.childNodes.length) card.appendChild(mlist);\n",
    "    }\n",
    "    container.appendChild(card);\n",
    "  }\n",
    "\n",
    "  function render() {\n",
    "    var sidebar = document.getElementById(\"sidebar-nav\");\n",
    "    var main = document.getElementById(\"main-content\");\n",
    "    sidebar.innerHTML = \"\";\n",
    "    main.innerHTML = \"\";\n",
    "    var shown = 0;\n",
    "    DOC.files.forEach(function (fname, fi) {\n",
    "      var top = topLevelForFile(fi).filter(declVisible);\n",
    "      if (!top.length) return;\n",
    "      shown += top.length;\n",
    "      sidebar.appendChild(el(\"div\", \"nav-file\", fname));\n",
    "      var heading = el(\"h2\", \"file-heading\", fname);\n",
    "      heading.id = \"file-\" + fi;\n",
    "      main.appendChild(heading);\n",
    "      top.forEach(function (i) {\n",
    "        renderNavItem(sidebar, i);\n",
    "        renderCard(main, i);\n",
    "      });\n",
    "    });\n",
    "    if (!shown) main.appendChild(el(\"p\", \"empty-state\", \"No declarations match the current filters.\"));\n",
    "  }\n",
    "\n",
    "  function initLangSwitcher() {\n",
    "    var langs = collectLangs();\n",
    "    var wrap = document.getElementById(\"lang-switcher\");\n",
    "    if (langs.length < 2) { wrap.style.display = \"none\"; return; }\n",
    "    var select = document.getElementById(\"lang-select\");\n",
    "    var srcOpt = document.createElement(\"option\");\n",
    "    srcOpt.value = \"\";\n",
    "    srcOpt.textContent = \"Source\";\n",
    "    select.appendChild(srcOpt);\n",
    "    langs.forEach(function (lg) {\n",
    "      var opt = document.createElement(\"option\");\n",
    "      opt.value = lg;\n",
    "      opt.textContent = lg;\n",
    "      select.appendChild(opt);\n",
    "    });\n",
    "    select.addEventListener(\"change\", function () {\n",
    "      state.lang = select.value;\n",
    "      render();\n",
    "    });\n",
    "  }\n",
    "\n",
    "  function initTheme() {\n",
    "    var saved = null;\n",
    "    try { saved = localStorage.getItem(\"salam-doc-theme\"); } catch (e) {}\n",
    "    if (saved === \"dark\" || saved === \"light\") document.documentElement.setAttribute(\"data-theme\", saved);\n",
    "    var btn = document.getElementById(\"theme-toggle\");\n",
    "    btn.addEventListener(\"click\", function () {\n",
    "      var cur = document.documentElement.getAttribute(\"data-theme\");\n",
    "      var next;\n",
    "      if (cur === \"dark\") next = \"light\";\n",
    "      else if (cur === \"light\") next = \"dark\";\n",
    "      else {\n",
    "        var prefersDark = window.matchMedia && window.matchMedia(\"(prefers-color-scheme: dark)\").matches;\n",
    "        next = prefersDark \? \"light\" : \"dark\";\n",
    "      }\n",
    "      document.documentElement.setAttribute(\"data-theme\", next);\n",
    "      try { localStorage.setItem(\"salam-doc-theme\", next); } catch (e) {}\n",
    "    });\n",
    "  }\n",
    "\n",
    "  function init() {\n",
    "    document.getElementById(\"doc-title\").textContent = DOC_TITLE;\n",
    "    document.title = DOC_TITLE + \" - API Documentation\";\n",
    "    document.getElementById(\"search-box\").addEventListener(\"input\", function (e) {\n",
    "      state.query = e.target.value;\n",
    "      render();\n",
    "    });\n",
    "    document.getElementById(\"show-private\").addEventListener(\"change\", function (e) {\n",
    "      state.showPrivate = e.target.checked;\n",
    "      render();\n",
    "    });\n",
    "    document.getElementById(\"sidebar-toggle\").addEventListener(\"click\", function () {\n",
    "      document.body.classList.toggle(\"sidebar-open\");\n",
    "    });\n",
    "    initLangSwitcher();\n",
    "    initTheme();\n",
    "    render();\n",
    "  }\n",
    "\n",
    "  init();\n",
    "})();\n",
    NULL};

const char *const doc_body_lines[] = {
    "<div class=\"topbar\">\n",
    "  <button id=\"sidebar-toggle\" class=\"icon-btn\" type=\"button\">Menu</button>\n",
    "  <span class=\"title\" id=\"doc-title\">salam doc</span>\n",
    "  <input type=\"search\" id=\"search-box\" placeholder=\"Search declarations...\">\n",
    "  <label><input type=\"checkbox\" id=\"show-private\"> Show private</label>\n",
    "  <div id=\"lang-switcher\"><select id=\"lang-select\"></select></div>\n",
    "  <button id=\"theme-toggle\" class=\"icon-btn\" type=\"button\">Theme</button>\n",
    "</div>\n",
    "<div class=\"layout\">\n",
    "  <aside class=\"sidebar\"><nav id=\"sidebar-nav\"></nav></aside>\n",
    "  <main id=\"main-content\"></main>\n",
    "</div>\n",
    NULL};
