#ifndef _STAGE_AST_ASTS_AST_PARAMETER_AST_PARAMETERS_AST_PARAMETERS_DIRECT_DESTROY_AST_PARAMETERS_DIRECT_DESTROY_H_
#define _STAGE_AST_ASTS_AST_PARAMETER_AST_PARAMETERS_AST_PARAMETERS_DIRECT_DESTROY_AST_PARAMETERS_DIRECT_DESTROY_H_

// base
#include <base.h>

// array
#include <utility/array/array_destroy/array_destroy.h>
#include <utility/array/type.h>

void ast_parameters_direct_destroy(ast_parameters_t parameters);

#endif  // _STAGE_AST_ASTS_AST_PARAMETER_AST_PARAMETERS_AST_PARAMETERS_DIRECT_DESTROY_AST_PARAMETERS_DIRECT_DESTROY_H_
