#ifndef _STAGE_VALIDATOR_VALIDATOR_VALIDATE_EXPRESSION_ITEM_VALIDATOR_VALIDATE_EXPRESSION_ITEM_H_
#define _STAGE_VALIDATOR_VALIDATOR_VALIDATE_EXPRESSION_ITEM_VALIDATOR_VALIDATE_EXPRESSION_ITEM_H_

// base
#include <base.h>

// ast
#include <stage/ast/type.h>

void validator_validate_expression_item(ast_t* ast);

#endif // _STAGE_VALIDATOR_VALIDATOR_VALIDATE_EXPRESSION_ITEM_VALIDATOR_VALIDATE_EXPRESSION_ITEM_H_
