// ----------- BEGIN AUTO GENERATED ----------- //
extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_size_default[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_appearance[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_color[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_width[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_height[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_aspect_ratio[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_backface_visibility[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_block_size[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_background_image[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_background_attachment[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_background_blend_mode[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_background_clip[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_background_origin[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_background_position_x[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_background_position_y[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_background_repeat[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_background_size[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_block_end_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_block_end_width[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_block_start_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_block_start_width[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_bottom_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_collapse[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_image_repeat[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_image_source[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_image_width[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_inline_end_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_inline_start_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_left_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_right_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_border_top_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_bottom[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_box_sizing[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_break_inside[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_break_before[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_break_after[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_caption_side[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_clear[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_clip_path[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_clip_rule[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_color_interpolation[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_color_interpolation_filters[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_color_scheme[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_column_count[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_column_fill[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_column_rule_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_column_span[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_contain[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_contain_intrinsic_block_size[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_contain_intrinsic_height[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_contain_intrinsic_inline_size[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_contain_intrinsic_size[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_contain_intrinsic_width[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_container[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_container_name[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_container_type[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_content[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_content_visibility[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_counter_increment[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_counter_set[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_cursor[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_direction[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_display[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_align_items[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_empty_cells[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_fill[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_fill_rule[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_filter[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_flex[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_flex_basis[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_flex_direction[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_flex_flow[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_flex_wrap[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_float[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font_display[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font_family[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font_feature_settings[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font_kerning[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font_language_override[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font_optical_sizing[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font_stretch[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font_variant[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_font_weight[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_area[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_auto_columns[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_auto_flow[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_auto_rows[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_column[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_column_end[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_column_start[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_row[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_row_end[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_row_start[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_template[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_template_areas[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_template_columns[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_grid_template_rows[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_height[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_justify_content[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_left[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_list_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_margin[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_margin_bottom[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_margin_left[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_margin_right[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_margin_top[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_object_fit[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_padding[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_text_decoration[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_z_index[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_outline_color[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_outline_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_outline_width[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_overflow[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_overflow_anchor[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_overflow_block[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_overflow_inline[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_overflow_wrap[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_overflow_x[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_overflow_y[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_padding_block_end[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_padding_block_start[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_padding_bottom[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_padding_inline[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_padding_inline_end[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_padding_inline_start[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_padding_left[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_padding_right[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_padding_top[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_page[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_page_break_after[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_page_break_before[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_page_break_inside[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_paint_order[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_perspective[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_place_content[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_place_items[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_place_self[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_pointer_events[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_position[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_print_color_adjust[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_quotes[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_resize[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_right[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_rotate[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_ruby_align[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_ruby_position[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_scroll_behavior[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_scroll_snap_align[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_scroll_snap_type[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_shape_outside[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_text_align[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_text_align_last[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_text_indent[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_text_transform[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_top[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_transform[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_unicode_bidi[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_user_select[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_width[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_will_change[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_transform_box[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_transform_origin[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_transform_style[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_transition[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_transition_behavior[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_transition_delay[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_transition_duration[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_transition_property[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_transition_timing_function[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_vector_effect[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_vertical_align[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_visibility[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_white_space[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_word_break[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_writing_mode[];

extern const ast_layout_attribute_pair_t ast_layout_allowed_style_list_zoom[];

// ----------- END AUTO GENERATED ----------- //

















