// ----------- BEGIN AUTO GENERATED ----------- //
ADD_BLOCK_TYPE(AST_BLOCK_TYPE_LAYOUT, "LAYOUT", "layout")

ADD_BLOCK_TYPE(AST_BLOCK_TYPE_FUNCTION, "FUNCTION", "function")

ADD_BLOCK_TYPE(AST_BLOCK_TYPE_IF, "IF", "if")

ADD_BLOCK_TYPE(AST_BLOCK_TYPE_ELSE_IF, "ELSE_IF", "else_if")

ADD_BLOCK_TYPE(AST_BLOCK_TYPE_ERROR, "ERROR", "error")

// ----------- END AUTO GENERATED ----------- //









