// ----------- BEGIN AUTO GENERATED ----------- //
ADD_VALUE_KIND(AST_TYPE_KIND_VOID, "VOID", "void")
ADD_VALUE_KIND(AST_TYPE_KIND_INT, "INT", "int")
ADD_VALUE_KIND(AST_TYPE_KIND_FLOAT, "FLOAT", "float")
ADD_VALUE_KIND(AST_TYPE_KIND_CHAR, "CHAR", "char")
ADD_VALUE_KIND(AST_TYPE_KIND_NULL, "NULL", "null")
ADD_VALUE_KIND(AST_TYPE_KIND_STRING, "STRING", "string")
ADD_VALUE_KIND(AST_TYPE_KIND_BOOL, "BOOL", "bool")
ADD_VALUE_KIND(AST_TYPE_KIND_STRUCT, "STRUCT", "struct")
ADD_VALUE_KIND(AST_TYPE_KIND_ENUM, "ENUM", "enum")
ADD_VALUE_KIND(AST_TYPE_KIND_POINTER, "POINTER", "pointer")
ADD_VALUE_KIND(AST_TYPE_KIND_ARRAY, "ARRAY", "array")
ADD_VALUE_KIND(AST_TYPE_KIND_FUNCTION, "FUNCTION", "function")
// ----------- END AUTO GENERATED ----------- //
