// ----------- BEGIN AUTO GENERATED ----------- //
ADD_TYPE(AST_TYPE_BLOCK, "BLOCK", "block")

ADD_TYPE(AST_TYPE_IF, "IF", "if")

ADD_TYPE(AST_TYPE_ELSE_IF, "ELSE_IF", "else_if")

ADD_TYPE(AST_TYPE_RETURN, "RETURN", "return")

ADD_TYPE(AST_TYPE_IMPORT, "IMPORT", "import")

ADD_TYPE(AST_TYPE_PRINT, "PRINT", "print")

ADD_TYPE(AST_TYPE_FUNCTION, "FUNCTION", "function")

ADD_TYPE(AST_TYPE_LAYOUT, "LAYOUT", "layout")

ADD_TYPE(AST_TYPE_ERROR, "ERROR", "error")

// ----------- END AUTO GENERATED ----------- //




