// ----------- BEGIN AUTO GENERATED ----------- //
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_BOOL,
                                  "BOOL", "bool")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_GROUP,
                                  "GROUP", "group")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_SIZE,
                                  "SIZE", "size")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_COLOR,
                                  "COLOR", "color")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_SIZES,
                                  "SIZES", "sizes")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_COLORS,
                                  "COLORS", "colors")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_SIZES124,
                                  "SIZES_124", "sizes-124")

ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_SIZE_COLOR,
                                  "SIZE_COLOR", "size_color")
ADD_LAYOUT_ATTRIBUTE_FILTER(
    AST_LAYOUY_ATTRIBUTE_FILTER_SIZES_COLORS, "SIZES_COLORS",
    "sizes_colors")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_STRING,
                                  "STRING", "string")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_PERCENTAGE,
                                  "PERCENTAGE", "percentage")
ADD_LAYOUT_ATTRIBUTE_FILTER(
    AST_LAYOUY_ATTRIBUTE_FILTER_POSITIVE_PERCENTAGE,
    "POSITIVE_PERCENTAGE", "positive_percentage")
ADD_LAYOUT_ATTRIBUTE_FILTER(
    AST_LAYOUY_ATTRIBUTE_FILTER_NEGATIVE_PERCENTAGE,
    "NEGATIVE_PERCENTAGE", "negative_percentage")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_PIXEL,
                                  "PIXEL", "pixel")

ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_NUMBER,
                                  "NUMBER", "number")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_INTEGER,
                                  "INTEGER", "integer")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_FLOAT,
                                  "FLOAT", "float")

ADD_LAYOUT_ATTRIBUTE_FILTER(
    AST_LAYOUY_ATTRIBUTE_FILTER_POSITIVE_NUMBER, "POSITIVE_NUMBER",
    "positive_number")
ADD_LAYOUT_ATTRIBUTE_FILTER(
    AST_LAYOUY_ATTRIBUTE_FILTER_POSITIVE_INTEGER, "POSITIVE_INTEGER",
    "positive_integer")
ADD_LAYOUT_ATTRIBUTE_FILTER(
    AST_LAYOUY_ATTRIBUTE_FILTER_POSITIVE_FLOAT, "POSITIVE_FLOAT",
    "positive_float")

ADD_LAYOUT_ATTRIBUTE_FILTER(
    AST_LAYOUY_ATTRIBUTE_FILTER_NEGATIVE_NUMBER, "NEGATIVE_NUMBER",
    "negative_number")
ADD_LAYOUT_ATTRIBUTE_FILTER(
    AST_LAYOUY_ATTRIBUTE_FILTER_NEGATIVE_INTEGER, "NEGATIVE_INTEGER",
    "negative_integer")
ADD_LAYOUT_ATTRIBUTE_FILTER(
    AST_LAYOUY_ATTRIBUTE_FILTER_NEGATIVE_FLOAT, "NEGATIVE_FLOAT",
    "negative_float")

ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_TIME,
                                  "TIME", "time")

ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_STRING_ANY,
                                  "STRING_ANY", "string_any")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_STRINGS_ANY,
                                  "STRINGS_ANY", "strings_any")
ADD_LAYOUT_ATTRIBUTE_FILTER(AST_LAYOUY_ATTRIBUTE_FILTER_ERROR,
                                  "ERROR", "error")
// ----------- END AUTO GENERATED ----------- //
