#ifndef _STAGE_AST_ASTS_AST_STATEMENT_AST_TYPE_STATEMENT_RAW_AST_TYPE_STATEMENT_RAW_CREATE_AST_TYPE_STATEMENT_RAW_CREATE_H_
#define _STAGE_AST_ASTS_AST_STATEMENT_AST_TYPE_STATEMENT_RAW_AST_TYPE_STATEMENT_RAW_CREATE_AST_TYPE_STATEMENT_RAW_CREATE_H_

// base
#include <base.h>

// string
#include <utility/string/string_duplicate/string_duplicate.h>

// ast
#include <stage/ast/type.h>

ast_t* ast_statement_raw_create(token_t* token);

#endif // _STAGE_AST_ASTS_AST_STATEMENT_AST_TYPE_STATEMENT_RAW_AST_TYPE_STATEMENT_RAW_CREATE_AST_TYPE_STATEMENT_RAW_CREATE_H_
