#!/usr/bin/env python3
"""
Generate web/keywords.js — the editor's syntax-highlight vocabulary — directly
from the compiler sources, so it never drifts from the real language.
Sources of truth (single place each):
  - keywords        src/langpack/langpack_data.c   ({ TK_KW_*, "spelling" }, en+fa)
  - primitive types src/semantic/types.c           ({ "name", TY_* }, en+fa)
  - layout elements std/layout/elements/*.salam     (@en / @fa annotations)
Output: web/keywords.js defining `window.SALAM_LEX = { kw, el, ty }`, which
app.js merges into its highlight sets. Run it directly, or let tools/build-wasm.sh
run it before each WASM build.
    python tools/gen-editor-keywords.py
"""
import glob, json, os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as f:
        return f.read()
def uniq(xs):
    seen, out = set(), []
    for x in xs:
        if x and x not in seen:
            seen.add(x); out.append(x)
    return out
kw = []
for m in re.finditer(r'\{\s*TK_KW_\w+\s*,\s*"((?:[^"\\]|\\.)*)"', read("src/langpack/langpack_data.c")):
    s = m.group(1)
    if s and not set(s) <= {"_"}:
        kw.append(s)
ty = [m.group(1) for m in re.finditer(r'\{\s*"([^"]+)"\s*,\s*TY_\w+\s*\}', read("src/semantic/types.c"))]
ty += ["auto", "خودکار", "byte", "HashMap", "Vector", "MapIter"]
el = []
STR = r'"((?:[^"\\]|\\.)*)"'
for f in sorted(glob.glob(os.path.join(ROOT, "std/layout/elements/*.salam"))):
    with open(f, encoding="utf-8") as fh:
        t = fh.read()
    for m in re.finditer(r'@en\s+(\[[^\]]*\]|' + STR + r')', t):
        first = re.search(STR, m.group(1))
        if first and " " not in first.group(1):
            el.append(first.group(1))
    for m in re.finditer(r'@fa\s+(\[[^\]]*\]|' + STR + r')', t):
        for s in re.findall(STR, m.group(1)):
            if " " not in s:
                el.append(s)
kw, ty, el = uniq(kw), uniq(ty), uniq(el)
banner = ("// AUTO-GENERATED by tools/gen-editor-keywords.py from the compiler sources.\n"
          "// Do NOT edit by hand — run `python tools/gen-editor-keywords.py`\n"
          "// (tools/build-wasm.sh runs it automatically). Sources: src/langpack/langpack_data.c,\n"
          "// src/semantic/types.c, std/layout/elements/*.salam.\n")
js = (banner +
      "window.SALAM_LEX = {\n"
      "  kw: " + json.dumps(kw, ensure_ascii=False) + ",\n"
      "  ty: " + json.dumps(ty, ensure_ascii=False) + ",\n"
      "  el: " + json.dumps(el, ensure_ascii=False) + "\n"
      "};\n")
out = os.path.join(ROOT, "web", "keywords.js")
with open(out, "w", encoding="utf-8") as f:
    f.write(js)
print("wrote web/keywords.js: %d keywords, %d types, %d elements" % (len(kw), len(ty), len(el)))
