name = "runner"
main = "src/index.ts"
compatibility_date = "2026-07-01"

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[observability.logs]
enabled = false
invocation_logs = true
