name = "runner"
main = "src/index.ts"
compatibility_date = "2026-07-01"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[[containers]]
class_name = "SalamSandbox"
image = "./container/Dockerfile"
max_instances = 10
instance_type = "basic"

[[durable_objects.bindings]]
class_name = "SalamSandbox"
name = "SALAM_SANDBOX"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SalamSandbox"]

[[ratelimits]]
name = "RUNNER_RATE_LIMITER"
namespace_id = "1001"

[ratelimits.simple]
limit = 20
period = 60
