// ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(TYPE, NAME, NAME_LOWER, ENDUSER_NAME, GENERATED_NAME, FILTER, ALLOWED_VALUES, SUBTAGS)

ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_BACKGROUND, "STYLE_BACKGROUND", "style_background", "زمینه", "background", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_COLOR, NULL, NULL)
ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_COLOR, "STYLE_COLOR", "style_color", "رنگ", "color", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_COLOR, NULL, NULL)
ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_FONT_SIZE, "STYLE_FONT_SIZE", "style_font_size", "اندازه", "font-size", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_SIZE, NULL, NULL)
ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_TOP, "STYLE_TOP", "style_top", "بالا", "size", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_SIZE, NULL, NULL)
ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_RIGHT, "STYLE_RIGHT", "style_right", "راست", "right", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_SIZE, NULL, NULL)
ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_LEFT, "STYLE_LEFT", "style_left", "چپ", "left", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_SIZE, NULL, NULL)
ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_BOTTOM, "STYLE_BOTTOM", "style_bottom", "پایین", "bottom", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_SIZE, NULL, NULL)

ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_MARGIN_TOP, "STYLE_MARGIN_TOP", "style_margin_top", "فضا بالا", "margin-top", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_SIZE, NULL, NULL)
ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_MARGIN_BOTTOM, "STYLE_MARGIN_BOTTOM", "style_margin_bottom", "فضا پایین", "margin-bottom", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_SIZE, NULL, NULL)
ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_MARGIN_LEFT, "STYLE_MARGIN_LEFT", "style_margin_left", "فضا چپ", "margin-left", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_SIZE, NULL, NULL)
ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_MARGIN_RIGHT, "STYLE_MARGIN_RIGHT", "style_margin_right", "فضا راست", "margin-right", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_SIZE, NULL, NULL)

ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_DISPLAY, "STYLE_DISPLAY", "style_display", "نمایش", "display", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_STRING, ast_layout_allowed_style_display, NULL)

ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE_HIDE(AST_LAYOUT_ATTRIBUTE_TYPE_ERROR, "ERROR", "error", "error", "error", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_STRING, NULL, NULL)
