// Paragraph Types
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_PARAGRAPH, "PARAGRAPH", "paragraph")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_PARAGRAPH_RAW, "PARAGRAPH_RAW", "paragraph_raw")

// Form Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BUTTON, "BUTTON", "button")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_INPUT, "INPUT", "input")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TEXTAREA, "TEXTAREA", "textarea")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_LABEL, "LABEL", "label")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SELECT, "SELECT", "select")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_OPTION, "OPTION", "option")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_FIELDSET, "FIELDSET", "fieldset")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_LEGEND, "LEGEND", "legend")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_FORM, "FORM", "form")

// Text Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SPAN, "SPAN", "span")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_STRONG, "STRONG", "strong")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_EM, "EM", "em")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_ITALIC, "ITALIC", "italic")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BOLD, "BOLD", "bold")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_UNDERLINE, "UNDERLINE", "underline")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SMALL, "SMALL", "small")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BIG, "BIG", "big")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SUB, "SUB", "sub")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SUP, "SUP", "sup")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_S, "S", "s")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_CENTER, "CENTER", "center")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_MARK, "MARK", "mark")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_Q, "Q", "q")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_CITE, "CITE", "cite")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_DFN, "DFN", "dfn")

// Sectioning Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_HEADER)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_FOOTER)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_NAV)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_MAIN)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SECTION)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_ARTICLE)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_ASIDE)

// Multimedia Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_VIDEO, "VIDEO", "video")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_AUDIO, "AUDIO", "audio")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_IMG, "IMG", "img")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_IFRAME, "IFRAME", "iframe")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_CANVAS, "CANVAS", "canvas")

// Interactive Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_DETAILS, "DETAILS", "details")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SUMMARY, "SUMMARY", "summary")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_DIALOG, "DIALOG", "dialog")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_MENU, "MENU", "menu")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_MENUITEM, "MENUITEM", "menuitem")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_COMMAND, "COMMAND", "command")

// List Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_UL, "UL", "ul")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_OL, "OL", "ol")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_LI, "LI", "li")

// Table Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE, "TABLE", "table")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_HEADER, "TABLE_HEADER", "table_header")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_BODY, "TABLE_BODY", "table_body")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_FOOTER, "TABLE_FOOTER", "table_footer")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_TR, "TABLE_TR", "table_tr")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_TD, "TABLE_TD", "table_td")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_TH, "TABLE_TH", "table_th")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_CAPTION, "CAPTION", "caption")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_COL, "COL", "col")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_COLGROUP, "COLGROUP", "colgroup")

// Miscellaneous Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BLOCKQUOTE, "BLOCKQUOTE", "blockquote")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_PRE, "PRE", "pre")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_CODE, "CODE", "code")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BR, "BR", "br")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_HR, "HR", "hr")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_DEL, "DEL", "del")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_INS, "INS", "ins")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_ADDRESS, "ADDRESS", "address")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TIME, "TIME", "time")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_PROGRESS, "PROGRESS", "progress")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_METER, "METER", "meter")

// Script and Style Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SCRIPT, "SCRIPT", "script")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_STYLE, "STYLE", "style")

// Special Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_DIV, "DIV", "div")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_LINK, "LINK", "link")

// Utility Elements
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_NONE, "NONE", "none")
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_ERROR, "ERROR", "error")
