// ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(TYPE, NAME, NAME_LOWER, ENDUSER_NAME, GENERATED_NAME, FILTER, ALLOWED_VALUES, SUBTAGS)

ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_BACKGROUND, "STYLE_BACKGROUND", "style_background", "زمینه", "background", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_COLOR, allowed_background_colors, NULL)
ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE(AST_LAYOUT_ATTRIBUTE_TYPE_STYLE_COLOR, "STYLE_COLOR", "style_color", "رنگ", "color", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_COLOR, allowed_background_colors, NULL)

ADD_LAYOUT_ATTRIBUTE_STYLE_TYPE_HIDE(AST_LAYOUT_ATTRIBUTE_TYPE_ERROR, "ERROR", "error", "error", "error", AST_LAYOUY_ATTRIBUTE_STYLE_FILTER_STRING, NULL, NULL)
