ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_GLOBAL, "GLOBAL", "global", "سراسری",
    "*")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_HOVER, "HOVER", "hover", "هاور",
    "hover")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ACTIVE, "ACTIVE", "active", "فعال",
    "active")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS, "FOCUS", "focus", "فوكوس",
    "focus")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_VISITED, "VISITED", "visited",
    "بازديد", "visited")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LINK, "LINK", "link", "لينك", "link")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS_VISIBLE, "FOCUS_VISIBLE",
    "focus_visible", "فوكوس قابل مشاهده", "focus-visible")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FOCUS_WITHIN, "FOCUS_WITHIN",
    "focus_within", "فوكوس داخلي", "focus-within")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_CHECKED, "CHECKED", "checked",
    "انتخاب", "checked")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_DISABLED, "DISABLED", "disabled",
    "غيرفعال", "disabled")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ENABLED, "ENABLED", "enabled", "فعال",
    "enabled")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_REQUIRED, "REQUIRED", "required",
    "ضروري", "required")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_OPTIONAL, "OPTIONAL", "optional",
    "اختياري", "optional")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_READ_ONLY, "READ_ONLY", "read_only",
    "فقط خواندني", "read-only")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_READ_WRITE, "READ_WRITE",
    "read_write", "قابل نوشتن", "read-write")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_VALID, "VALID", "valid", "معتبر",
    "valid")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_INVALID, "INVALID", "invalid",
    "نامعتبر", "invalid")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_IN_RANGE, "IN_RANGE", "in_range",
    "در محدوده", "in-range")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_OUT_OF_RANGE, "OUT_OF_RANGE",
    "out_of_range", "خارج از محدوده", "out-of-range")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_PLACEHOLDER_SHOWN,
    "PLACEHOLDER_SHOWN", "placeholder_shown", "نمايش جايگير",
    "placeholder-shown")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_BLANK, "BLANK", "blank", "خالي",
    "blank")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_TARGET, "TARGET", "target", "هدف",
    "target")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ROOT, "ROOT", "root", "ريشه", "root")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_CHILD, "NTH_CHILD", "nth_child",
    "فرزند nام", "nth-child")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_LAST_CHILD, "NTH_LAST_CHILD",
    "nth_last_child", "آخرين فرزند nام", "nth-last-child")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_OF_TYPE, "NTH_OF_TYPE",
    "nth_of_type", "نوع nام", "nth-of-type")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NTH_LAST_OF_TYPE, "NTH_LAST_OF_TYPE",
    "nth_last_of_type", "آخرين نوع nام", "nth-last-of-type")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FIRST_CHILD, "FIRST_CHILD",
    "first_child", "اولين فرزند", "first-child")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LAST_CHILD, "LAST_CHILD",
    "last_child", "آخرين فرزند", "last-child")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_FIRST_OF_TYPE, "FIRST_OF_TYPE",
    "first_of_type", "اولين نوع", "first-of-type")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LAST_OF_TYPE, "LAST_OF_TYPE",
    "last_of_type", "آخرين نوع", "last-of-type")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ONLY_CHILD, "ONLY_CHILD",
    "only_child", "تنها فرزند", "only-child")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ONLY_OF_TYPE, "ONLY_OF_TYPE",
    "only_of_type", "تنها نوع", "only-of-type")
ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_EMPTY, "EMPTY", "empty", "خالي",
    "empty")

// ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_NOT,
// "NOT", "not", "نه", "not")
// ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_IS,
// "IS", "is", "است", "is")
// ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_WHERE,
// "WHERE", "where", "جايي كه", "where")
// ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_DIR,
// "DIR", "dir", "جهت", "dir")
// ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_LANG,
// "LANG", "lang", "زبان", "lang")
// ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_HAS,
// "HAS", "has", "دارد", "has")

ADD_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE(
    AST_LAYOUT_ATTRIBUTE_STYLE_STATE_TYPE_ERROR, "ERROR", "error", "", "")
