// SIGNATURE: ADD_LAYOUT_TYPE(TYPE, NAME, NAME_LOWER, GENERATED_NAME,
// ENDUSER_NAME, IS_SINGLE_TAG)

// ----------- BEGIN AUTO GENERATED ----------- //
ADD_LAYOUT_TYPE_HIDE(AST_LAYOUT_TYPE_PARAGRAPH_RAW, "PARAGRAPH_RAW", "content", "محتوا", false)
ADD_LAYOUT_TYPE_HIDE(AST_LAYOUT_TYPE_ERROR, "ERROR", "error", "خطا", false)
ADD_LAYOUT_TYPE_HIDE(AST_LAYOUT_TYPE_NONE, "NONE", "layout", "صفحه", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_PARAGRAPH, "PARAGRAPH", "p", "paragraph", "پاراگراف", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BUTTON, "BUTTON", "button", "button", "دکمه", true)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TEXTAREA, "TEXTAREA", "textarea", "textarea", "['ویرایشگرمتن', 'ویرایشگر متن']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_LABEL, "LABEL", "label", "label", "برچسب", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SELECT, "SELECT", "select", "select", "فهرست کشویی", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_FIELDSET, "FIELDSET", "fieldset", "fieldset", "['گروه\u200cبندی', 'گروه بندی']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_LEGEND, "LEGEND", "legend", "legend", "عنوان گروه", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_FORM, "FORM", "form", "form", "فرم", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_OPTGROUP, "OPTGROUP", "optgroup", "optgroup", "گروه انتخاب", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_DATALIST, "DATALIST", "datalist", "datalist", "داده فهرست", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_OUTPUT, "OUTPUT", "output", "output", "خروجی", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_KEYGEN, "KEYGEN", "keygen", "keygen", "تولید کلید", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SPAN, "SPAN", "span", "span", "قطعه", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_STRONG, "STRONG", "strong", "strong", "ضخیم مهم", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_EM, "EM", "em", "em", "ایتالیک پیشرفته", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_ITALIC, "ITALIC", "i", "italic", "ایتالیک", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BOLD, "BOLD", "b", "bold", "ضخیم", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SUBTITLE, "SUBTITLE", "subtitle", "subtitle", "['سرتیتر', 'سر تیتر']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_UNDERLINE, "UNDERLINE", "u", "underline", "['زیرخط', 'زیر خط']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SMALL, "SMALL", "small", "small", "کوچک", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BIG, "BIG", "big", "big", "بزرگ", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SUB, "SUB", "sub", "sub", "زیرین", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SUP, "SUP", "sup", "sup", "رویین", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_S, "S", "s", "s", "خط خورده", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_MARK, "MARK", "mark", "mark", "['علامتگذاری', 'علامت گذاری']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_Q, "Q", "q", "q", "['نقل قول', 'نقل\u200cقول']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_CITE, "CITE", "cite", "cite", "['اثر', 'ارجاع']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_DFN, "DFN", "dfn", "dfn", "اصطلاح", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_ABBR, "ABBR", "abbr", "abbr", "اختصار", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_KBD, "KBD", "kbd", "kbd", "['ورودی صفحه نمایش', 'ورودی کیبورد']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SAMP, "SAMP", "samp", "samp", "نمونه", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_VAR, "VAR", "var", "var", "متغیر", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_RUBY, "RUBY", "ruby", "ruby", "روبین", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_RT, "RT", "rt", "rt", "متن روبین", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_RP, "RP", "rp", "rp", "جایگزین روبین", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BDI, "BDI", "bdi", "bdi", "جداگانه", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BDO, "BDO", "bdo", "bdo", "جهت دهی", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_WBR, "WBR", "wbr", "wbr", "شکستن کلمه", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_HEADER, "HEADER", "header", "header", "['سربخش', 'سر بخش']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_FOOTER, "FOOTER", "footer", "footer", "['پاصفحه', 'پا صفحه']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_NAV, "NAV", "nav", "nav", "ناوبری", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SECTION, "SECTION", "section", "section", "بخش", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_ARTICLE, "ARTICLE", "article", "article", "مقاله", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_ASIDE, "ASIDE", "aside", "aside", "['جداگانه', 'جدا گانه']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_MAIN, "MAIN", "main", "main", "اصلی", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_HGROUP, "HGROUP", "hgroup", "hgroup", "['گروه سربخش', 'گروه\u200cسربخش', 'گروه\u200cسر بخش', 'گروه سر بخش']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_FIGURE, "FIGURE", "figure", "figure", "شکل", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_FIGCAPTION, "FIGCAPTION", "figcaption", "figcaption", "زیرنویس شکل", false)
ADD_LAYOUT_TYPE_REPEAT(AST_LAYOUT_TYPE_FIGCAPTION, "FIGCAPTION", "figcaption", "figcaption", "زیر نویس شکل", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_VIDEO, "VIDEO", "video", "video", "فیلم", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_AUDIO, "AUDIO", "audio", "audio", "صدا", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_IFRAME, "IFRAME", "iframe", "iframe", "سایت", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_CANVAS, "CANVAS", "canvas", "canvas", "گرافیکی", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_DETAILS, "DETAILS", "details", "details", "جزئیات", false)
ADD_LAYOUT_TYPE_REPEAT(AST_LAYOUT_TYPE_DETAILS, "DETAILS", "details", "details", "جزییات", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_SUMMARY, "SUMMARY", "summary", "summary", "خلاصه", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_DIALOG, "DIALOG", "dialog", "dialog", "دیالوگ", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_MENU, "MENU", "menu", "menu", "منو", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_MENUITEM, "MENUITEM", "menuitem", "menuitem", "آیتم منو", false)
ADD_LAYOUT_TYPE_REPEAT(AST_LAYOUT_TYPE_MENUITEM, "MENUITEM", "menuitem", "menuitem", "مورد منو", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_COMMAND, "COMMAND", "command", "command", "فرمان", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_UL, "UL", "ul", "ul", "فهرست غیرمرتب", false)
ADD_LAYOUT_TYPE_REPEAT(AST_LAYOUT_TYPE_UL, "UL", "ul", "ul", "فهرست غیر مرتب", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_OL, "OL", "ol", "ol", "فهرست مرتب", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_LI, "LI", "li", "li", "مورد", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE, "TABLE", "table", "table", "جدول", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_HEADER, "TABLE_HEADER", "thead", "table-header", "سرجدول", false)
ADD_LAYOUT_TYPE_REPEAT(AST_LAYOUT_TYPE_TABLE_HEADER, "TABLE_HEADER", "thead", "table-header", "سر جدول", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_BODY, "TABLE_BODY", "tbody", "table-body", "بدنه جدول", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_FOOTER, "TABLE_FOOTER", "tfoot", "table-footer", "پاصفحه جدول", false)
ADD_LAYOUT_TYPE_REPEAT(AST_LAYOUT_TYPE_TABLE_FOOTER, "TABLE_FOOTER", "tfoot", "table-footer", "پا صفحه جدول", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_TR, "TABLE_TR", "tr", "table-tr", "ردیف", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_TD, "TABLE_TD", "td", "table-td", "سلول", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_TABLE_TH, "TABLE_TH", "th", "table-th", "سرسلول", false)
ADD_LAYOUT_TYPE_REPEAT(AST_LAYOUT_TYPE_TABLE_TH, "TABLE_TH", "th", "th", "سر سلول", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_CAPTION, "CAPTION", "caption", "caption", "عنوان جدول", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_COL, "COL", "th", "col", "ستون", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_COLGROUP, "COLGROUP", "colgroup", "colgroup", "گروه ستون‌ها", false)
ADD_LAYOUT_TYPE_REPEAT(AST_LAYOUT_TYPE_COLGROUP, "COLGROUP", "colgroup", "colgroup", "['گروه ستون\u200c ها', 'گروه ستون\u200cها']", false)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_INCLUDE, "INCLUDE", "include", "include", "فراخوانی", true)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_BR, "BR", "br", "br", "خط بعدی", true)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_HR, "HR", "hr", "hr", "خط", true)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_INPUT, "INPUT", "input", "input", "ورودی", true)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_IMG, "IMG", "img", "img", "تصویر", true)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_FONT, "FONT", "font", "font", "قلم", true)
ADD_LAYOUT_TYPE(AST_LAYOUT_TYPE_MEDIA, "MEDIA", "@media", "responsive", "['واکنش گرا', 'واکنش\u200cگرا']", true)
// ----------- END AUTO GENERATED ----------- //

