#ifndef _BASE_ALL_H_
#define _BASE_ALL_H_
// Auto-generated header including all .h files

#include <stage/ast/ast_alloc/ast_alloc.h>
#include <stage/ast/ast_create/ast_create.h>
#include <stage/ast/ast_destroy/ast_destroy.h>
#include <stage/ast/ast_json/ast_json.h>
#include <stage/ast/ast_log/ast_log.h>
#include <stage/ast/ast_node_type_name/ast_node_type_name.h>
#include <stage/ast/ast_type/ast_type_destroy/ast_type_destroy.h>
#include <stage/ast/ast_type/ast_type_direct_destroy/ast_type_direct_destroy.h>
#include <stage/ast/ast_type/ast_type_direct_json/ast_type_direct_json.h>
#include <stage/ast/ast_type/ast_type_json/ast_type_json.h>
#include <stage/ast/asts/ast_argument/ast_argument_item/ast_argument_item_create/ast_argument_item_create.h>
#include <stage/ast/asts/ast_argument/ast_argument_item/ast_argument_item_destroy/ast_argument_item_destroy.h>
#include <stage/ast/asts/ast_argument/ast_argument_item/ast_argument_item_direct_destroy/ast_argument_item_direct_destroy.h>
#include <stage/ast/asts/ast_argument/ast_argument_item/ast_argument_item_direct_json/ast_argument_item_direct_json.h>
#include <stage/ast/asts/ast_argument/ast_argument_item/ast_argument_item_json/ast_argument_item_json.h>
#include <stage/ast/asts/ast_argument/ast_argument_item/ast_argument_item_log/ast_argument_item_log.h>
#include <stage/ast/asts/ast_argument/ast_arguments/ast_arguments_create/ast_arguments_create.h>
#include <stage/ast/asts/ast_argument/ast_arguments/ast_arguments_destroy/ast_arguments_destroy.h>
#include <stage/ast/asts/ast_argument/ast_arguments/ast_arguments_direct_destroy/ast_arguments_direct_destroy.h>
#include <stage/ast/asts/ast_argument/ast_arguments/ast_arguments_direct_json/ast_arguments_direct_json.h>
#include <stage/ast/asts/ast_argument/ast_arguments/ast_arguments_json/ast_arguments_json.h>
#include <stage/ast/asts/ast_argument/ast_arguments/ast_arguments_log/ast_arguments_log.h>
#include <stage/ast/asts/ast_attribute/ast_attribute_item/ast_attribute_item_create/ast_attribute_item_create.h>
#include <stage/ast/asts/ast_attribute/ast_attribute_item/ast_attribute_item_destroy/ast_attribute_item_destroy.h>
#include <stage/ast/asts/ast_attribute/ast_attribute_item/ast_attribute_item_direct_destroy/ast_attribute_item_direct_destroy.h>
#include <stage/ast/asts/ast_attribute/ast_attribute_item/ast_attribute_item_direct_json/ast_attribute_item_direct_json.h>
#include <stage/ast/asts/ast_attribute/ast_attribute_item/ast_attribute_item_json/ast_attribute_item_json.h>
#include <stage/ast/asts/ast_attribute/ast_attribute_item/ast_attribute_item_log/ast_attribute_item_log.h>
#include <stage/ast/asts/ast_attribute/ast_attributes/ast_attributes_create/ast_attributes_create.h>
#include <stage/ast/asts/ast_attribute/ast_attributes/ast_attributes_destroy/ast_attributes_destroy.h>
#include <stage/ast/asts/ast_attribute/ast_attributes/ast_attributes_direct_destroy/ast_attributes_direct_destroy.h>
#include <stage/ast/asts/ast_attribute/ast_attributes/ast_attributes_direct_json/ast_attributes_direct_json.h>
#include <stage/ast/asts/ast_attribute/ast_attributes/ast_attributes_json/ast_attributes_json.h>
#include <stage/ast/asts/ast_attribute/ast_attributes/ast_attributes_log/ast_attributes_log.h>
#include <stage/ast/asts/ast_block/ast_block_create/ast_block_create.h>
#include <stage/ast/asts/ast_block/ast_block_destroy/ast_block_destroy.h>
#include <stage/ast/asts/ast_block/ast_block_direct_destroy/ast_block_direct_destroy.h>
#include <stage/ast/asts/ast_block/ast_block_direct_json/ast_block_direct_json.h>
#include <stage/ast/asts/ast_block/ast_block_json/ast_block_json.h>
#include <stage/ast/asts/ast_block/ast_block_log/ast_block_log.h>
#include <stage/ast/asts/ast_expression/ast_expression_binary/ast_expression_binary_create/ast_expression_binary_create.h>
#include <stage/ast/asts/ast_expression/ast_expression_binary/ast_expression_binary_destroy/ast_expression_binary_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_binary/ast_expression_binary_direct_destroy/ast_expression_binary_direct_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_binary/ast_expression_binary_direct_json/ast_expression_binary_direct_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_binary/ast_expression_binary_json/ast_expression_binary_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_binary/ast_expression_binary_log/ast_expression_binary_log.h>
#include <stage/ast/asts/ast_expression/ast_expression_call/ast_expression_call_create/ast_expression_call_create.h>
#include <stage/ast/asts/ast_expression/ast_expression_call/ast_expression_call_destroy/ast_expression_call_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_call/ast_expression_call_direct_destroy/ast_expression_call_direct_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_call/ast_expression_call_direct_json/ast_expression_call_direct_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_call/ast_expression_call_json/ast_expression_call_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_call/ast_expression_call_log/ast_expression_call_log.h>
#include <stage/ast/asts/ast_expression/ast_expression_identifier/ast_expression_identifier_create/ast_expression_identifier_create.h>
#include <stage/ast/asts/ast_expression/ast_expression_identifier/ast_expression_identifier_destroy/ast_expression_identifier_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_identifier/ast_expression_identifier_direct_destroy/ast_expression_identifier_direct_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_identifier/ast_expression_identifier_direct_json/ast_expression_identifier_direct_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_identifier/ast_expression_identifier_json/ast_expression_identifier_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_identifier/ast_expression_identifier_log/ast_expression_identifier_log.h>
#include <stage/ast/asts/ast_expression/ast_expression_index/ast_expression_index_create/ast_expression_index_create.h>
#include <stage/ast/asts/ast_expression/ast_expression_index/ast_expression_index_destroy/ast_expression_index_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_index/ast_expression_index_direct_destroy/ast_expression_index_direct_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_index/ast_expression_index_direct_json/ast_expression_index_direct_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_index/ast_expression_index_json/ast_expression_index_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_index/ast_expression_index_log/ast_expression_index_log.h>
#include <stage/ast/asts/ast_expression/ast_expression_item/ast_expression_item_create/ast_expression_item_create.h>
#include <stage/ast/asts/ast_expression/ast_expression_item/ast_expression_item_destroy/ast_expression_item_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_item/ast_expression_item_direct_destroy/ast_expression_item_direct_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_item/ast_expression_item_direct_json/ast_expression_item_direct_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_item/ast_expression_item_json/ast_expression_item_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_item/ast_expression_item_log/ast_expression_item_log.h>
#include <stage/ast/asts/ast_expression/ast_expression_literal/ast_expression_literal_create/ast_expression_literal_create.h>
#include <stage/ast/asts/ast_expression/ast_expression_literal/ast_expression_literal_destroy/ast_expression_literal_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_literal/ast_expression_literal_direct_destroy/ast_expression_literal_direct_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_literal/ast_expression_literal_direct_json/ast_expression_literal_direct_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_literal/ast_expression_literal_json/ast_expression_literal_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_literal/ast_expression_literal_log/ast_expression_literal_log.h>
#include <stage/ast/asts/ast_expression/ast_expression_type_name/ast_expression_type_name.h>
#include <stage/ast/asts/ast_expression/ast_expression_unary/ast_expression_unary_create/ast_expression_unary_create.h>
#include <stage/ast/asts/ast_expression/ast_expression_unary/ast_expression_unary_destroy/ast_expression_unary_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_unary/ast_expression_unary_direct_destroy/ast_expression_unary_direct_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expression_unary/ast_expression_unary_direct_json/ast_expression_unary_direct_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_unary/ast_expression_unary_json/ast_expression_unary_json.h>
#include <stage/ast/asts/ast_expression/ast_expression_unary/ast_expression_unary_log/ast_expression_unary_log.h>
#include <stage/ast/asts/ast_expression/ast_expressions/ast_expressions_create/ast_expressions_create.h>
#include <stage/ast/asts/ast_expression/ast_expressions/ast_expressions_destroy/ast_expressions_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expressions/ast_expressions_direct_destroy/ast_expressions_direct_destroy.h>
#include <stage/ast/asts/ast_expression/ast_expressions/ast_expressions_direct_json/ast_expressions_direct_json.h>
#include <stage/ast/asts/ast_expression/ast_expressions/ast_expressions_json/ast_expressions_json.h>
#include <stage/ast/asts/ast_expression/ast_expressions/ast_expressions_log/ast_expressions_log.h>
#include <stage/ast/asts/ast_extern/ast_extern_decl/ast_extern_decl_create/ast_extern_decl_create.h>
#include <stage/ast/asts/ast_extern/ast_extern_decl/ast_extern_decl_destroy/ast_extern_decl_destroy.h>
#include <stage/ast/asts/ast_extern/ast_extern_decl/ast_extern_decl_direct_destroy/ast_extern_decl_direct_destroy.h>
#include <stage/ast/asts/ast_extern/ast_extern_decl/ast_extern_decl_direct_json/ast_extern_decl_direct_json.h>
#include <stage/ast/asts/ast_extern/ast_extern_decl/ast_extern_decl_json/ast_extern_decl_json.h>
#include <stage/ast/asts/ast_extern/ast_extern_decl/ast_extern_decl_log/ast_extern_decl_log.h>
#include <stage/ast/asts/ast_extern/ast_extern_function/ast_extern_function_create/ast_extern_function_create.h>
#include <stage/ast/asts/ast_extern/ast_extern_function/ast_extern_function_destroy/ast_extern_function_destroy.h>
#include <stage/ast/asts/ast_extern/ast_extern_function/ast_extern_function_direct_destroy/ast_extern_function_direct_destroy.h>
#include <stage/ast/asts/ast_extern/ast_extern_function/ast_extern_function_direct_json/ast_extern_function_direct_json.h>
#include <stage/ast/asts/ast_extern/ast_extern_function/ast_extern_function_json/ast_extern_function_json.h>
#include <stage/ast/asts/ast_extern/ast_extern_function/ast_extern_function_log/ast_extern_function_log.h>
#include <stage/ast/asts/ast_extern/ast_extern_type_name/ast_extern_type_name.h>
#include <stage/ast/asts/ast_extern/ast_extern_variable/ast_extern_variable_create/ast_extern_variable_create.h>
#include <stage/ast/asts/ast_extern/ast_extern_variable/ast_extern_variable_destroy/ast_extern_variable_destroy.h>
#include <stage/ast/asts/ast_extern/ast_extern_variable/ast_extern_variable_direct_destroy/ast_extern_variable_direct_destroy.h>
#include <stage/ast/asts/ast_extern/ast_extern_variable/ast_extern_variable_direct_json/ast_extern_variable_direct_json.h>
#include <stage/ast/asts/ast_extern/ast_extern_variable/ast_extern_variable_json/ast_extern_variable_json.h>
#include <stage/ast/asts/ast_extern/ast_extern_variable/ast_extern_variable_log/ast_extern_variable_log.h>
#include <stage/ast/asts/ast_extern/type.h>
#include <stage/ast/asts/ast_function_decl/ast_function_decl_create/ast_function_decl_create.h>
#include <stage/ast/asts/ast_function_decl/ast_function_decl_destroy/ast_function_decl_destroy.h>
#include <stage/ast/asts/ast_function_decl/ast_function_decl_direct_destroy/ast_function_decl_direct_destroy.h>
#include <stage/ast/asts/ast_function_decl/ast_function_decl_direct_json/ast_function_decl_direct_json.h>
#include <stage/ast/asts/ast_function_decl/ast_function_decl_json/ast_function_decl_json.h>
#include <stage/ast/asts/ast_function_decl/ast_function_decl_log/ast_function_decl_log.h>
#include <stage/ast/asts/ast_import/ast_import_create/ast_import_create.h>
#include <stage/ast/asts/ast_import/ast_import_destroy/ast_import_destroy.h>
#include <stage/ast/asts/ast_import/ast_import_direct_destroy/ast_import_direct_destroy.h>
#include <stage/ast/asts/ast_import/ast_import_direct_json/ast_import_direct_json.h>
#include <stage/ast/asts/ast_import/ast_import_json/ast_import_json.h>
#include <stage/ast/asts/ast_import/ast_import_log/ast_import_log.h>
#include <stage/ast/asts/ast_kind/ast_kind_decl/ast_kind_decl_create/ast_kind_decl_create.h>
#include <stage/ast/asts/ast_kind/ast_kind_decl/ast_kind_decl_destroy/ast_kind_decl_destroy.h>
#include <stage/ast/asts/ast_kind/ast_kind_decl/ast_kind_decl_direct_destroy/ast_kind_decl_direct_destroy.h>
#include <stage/ast/asts/ast_kind/ast_kind_decl/ast_kind_decl_direct_json/ast_kind_decl_direct_json.h>
#include <stage/ast/asts/ast_kind/ast_kind_decl/ast_kind_decl_json/ast_kind_decl_json.h>
#include <stage/ast/asts/ast_kind/ast_kind_decl/ast_kind_decl_log/ast_kind_decl_log.h>
#include <stage/ast/asts/ast_kind/ast_kind_decl/ast_kind_decl_type_name/ast_kind_decl_type_name.h>
#include <stage/ast/asts/ast_kind/ast_kind_enum/ast_kind_enum_create/ast_kind_enum_create.h>
#include <stage/ast/asts/ast_kind/ast_kind_enum/ast_kind_enum_destroy/ast_kind_enum_destroy.h>
#include <stage/ast/asts/ast_kind/ast_kind_enum/ast_kind_enum_direct_destroy/ast_kind_enum_direct_destroy.h>
#include <stage/ast/asts/ast_kind/ast_kind_enum/ast_kind_enum_direct_json/ast_kind_enum_direct_json.h>
#include <stage/ast/asts/ast_kind/ast_kind_enum/ast_kind_enum_json/ast_kind_enum_json.h>
#include <stage/ast/asts/ast_kind/ast_kind_enum/ast_kind_enum_log/ast_kind_enum_log.h>
#include <stage/ast/asts/ast_kind/ast_kind_struct/ast_kind_struct_create/ast_kind_struct_create.h>
#include <stage/ast/asts/ast_kind/ast_kind_struct/ast_kind_struct_destroy/ast_kind_struct_destroy.h>
#include <stage/ast/asts/ast_kind/ast_kind_struct/ast_kind_struct_direct_destroy/ast_kind_struct_direct_destroy.h>
#include <stage/ast/asts/ast_kind/ast_kind_struct/ast_kind_struct_direct_json/ast_kind_struct_direct_json.h>
#include <stage/ast/asts/ast_kind/ast_kind_struct/ast_kind_struct_json/ast_kind_struct_json.h>
#include <stage/ast/asts/ast_kind/ast_kind_struct/ast_kind_struct_log/ast_kind_struct_log.h>
#include <stage/ast/asts/ast_kind/ast_kind_union/ast_kind_union_create/ast_kind_union_create.h>
#include <stage/ast/asts/ast_kind/ast_kind_union/ast_kind_union_destroy/ast_kind_union_destroy.h>
#include <stage/ast/asts/ast_kind/ast_kind_union/ast_kind_union_direct_destroy/ast_kind_union_direct_destroy.h>
#include <stage/ast/asts/ast_kind/ast_kind_union/ast_kind_union_direct_json/ast_kind_union_direct_json.h>
#include <stage/ast/asts/ast_kind/ast_kind_union/ast_kind_union_json/ast_kind_union_json.h>
#include <stage/ast/asts/ast_kind/ast_kind_union/ast_kind_union_log/ast_kind_union_log.h>
#include <stage/ast/asts/ast_kind/type.h>
#include <stage/ast/asts/ast_package/ast_package_create/ast_package_create.h>
#include <stage/ast/asts/ast_package/ast_package_destroy/ast_package_destroy.h>
#include <stage/ast/asts/ast_package/ast_package_direct_destroy/ast_package_direct_destroy.h>
#include <stage/ast/asts/ast_package/ast_package_direct_json/ast_package_direct_json.h>
#include <stage/ast/asts/ast_package/ast_package_json/ast_package_json.h>
#include <stage/ast/asts/ast_package/ast_package_log/ast_package_log.h>
#include <stage/ast/asts/ast_parameter/ast_parameter_item/ast_parameter_item_create/ast_parameter_item_create.h>
#include <stage/ast/asts/ast_parameter/ast_parameter_item/ast_parameter_item_destroy/ast_parameter_item_destroy.h>
#include <stage/ast/asts/ast_parameter/ast_parameter_item/ast_parameter_item_direct_destroy/ast_parameter_item_direct_destroy.h>
#include <stage/ast/asts/ast_parameter/ast_parameter_item/ast_parameter_item_direct_json/ast_parameter_item_direct_json.h>
#include <stage/ast/asts/ast_parameter/ast_parameter_item/ast_parameter_item_json/ast_parameter_item_json.h>
#include <stage/ast/asts/ast_parameter/ast_parameter_item/ast_parameter_item_log/ast_parameter_item_log.h>
#include <stage/ast/asts/ast_parameter/ast_parameters/ast_parameters_create/ast_parameters_create.h>
#include <stage/ast/asts/ast_parameter/ast_parameters/ast_parameters_destroy/ast_parameters_destroy.h>
#include <stage/ast/asts/ast_parameter/ast_parameters/ast_parameters_direct_destroy/ast_parameters_direct_destroy.h>
#include <stage/ast/asts/ast_parameter/ast_parameters/ast_parameters_direct_json/ast_parameters_direct_json.h>
#include <stage/ast/asts/ast_parameter/ast_parameters/ast_parameters_json/ast_parameters_json.h>
#include <stage/ast/asts/ast_parameter/ast_parameters/ast_parameters_log/ast_parameters_log.h>
#include <stage/ast/asts/ast_program/ast_program_create/ast_program_create.h>
#include <stage/ast/asts/ast_program/ast_program_destroy/ast_program_destroy.h>
#include <stage/ast/asts/ast_program/ast_program_direct_destroy/ast_program_direct_destroy.h>
#include <stage/ast/asts/ast_program/ast_program_direct_json/ast_program_direct_json.h>
#include <stage/ast/asts/ast_program/ast_program_json/ast_program_json.h>
#include <stage/ast/asts/ast_program/ast_program_log/ast_program_log.h>
#include <stage/ast/asts/ast_statement/ast_statement_expression/ast_statement_expression_create/ast_statement_expression_create.h>
#include <stage/ast/asts/ast_statement/ast_statement_expression/ast_statement_expression_destroy/ast_statement_expression_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_expression/ast_statement_expression_direct_destroy/ast_statement_expression_direct_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_expression/ast_statement_expression_direct_json/ast_statement_expression_direct_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_expression/ast_statement_expression_json/ast_statement_expression_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_expression/ast_statement_expression_log/ast_statement_expression_log.h>
#include <stage/ast/asts/ast_statement/ast_statement_for/ast_statement_for_create/ast_statement_for_create.h>
#include <stage/ast/asts/ast_statement/ast_statement_for/ast_statement_for_destroy/ast_statement_for_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_for/ast_statement_for_direct_destroy/ast_statement_for_direct_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_for/ast_statement_for_direct_json/ast_statement_for_direct_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_for/ast_statement_for_json/ast_statement_for_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_for/ast_statement_for_log/ast_statement_for_log.h>
#include <stage/ast/asts/ast_statement/ast_statement_foreach/ast_statement_foreach_create/ast_statement_foreach_create.h>
#include <stage/ast/asts/ast_statement/ast_statement_foreach/ast_statement_foreach_destroy/ast_statement_foreach_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_foreach/ast_statement_foreach_direct_destroy/ast_statement_foreach_direct_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_foreach/ast_statement_foreach_direct_json/ast_statement_foreach_direct_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_foreach/ast_statement_foreach_json/ast_statement_foreach_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_foreach/ast_statement_foreach_log/ast_statement_foreach_log.h>
#include <stage/ast/asts/ast_statement/ast_statement_if/ast_statement_if_create/ast_statement_if_create.h>
#include <stage/ast/asts/ast_statement/ast_statement_if/ast_statement_if_destroy/ast_statement_if_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_if/ast_statement_if_direct_destroy/ast_statement_if_direct_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_if/ast_statement_if_direct_json/ast_statement_if_direct_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_if/ast_statement_if_json/ast_statement_if_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_if/ast_statement_if_log/ast_statement_if_log.h>
#include <stage/ast/asts/ast_statement/ast_statement_print/ast_statement_print_create/ast_statement_print_create.h>
#include <stage/ast/asts/ast_statement/ast_statement_print/ast_statement_print_destroy/ast_statement_print_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_print/ast_statement_print_direct_destroy/ast_statement_print_direct_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_print/ast_statement_print_direct_json/ast_statement_print_direct_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_print/ast_statement_print_json/ast_statement_print_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_print/ast_statement_print_log/ast_statement_print_log.h>
#include <stage/ast/asts/ast_statement/ast_statement_return/ast_statement_return_create/ast_statement_return_create.h>
#include <stage/ast/asts/ast_statement/ast_statement_return/ast_statement_return_destroy/ast_statement_return_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_return/ast_statement_return_direct_destroy/ast_statement_return_direct_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_return/ast_statement_return_direct_json/ast_statement_return_direct_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_return/ast_statement_return_json/ast_statement_return_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_return/ast_statement_return_log/ast_statement_return_log.h>
#include <stage/ast/asts/ast_statement/ast_statement_variable_decl/ast_statement_variable_decl_create/ast_statement_variable_decl_create.h>
#include <stage/ast/asts/ast_statement/ast_statement_variable_decl/ast_statement_variable_decl_destroy/ast_statement_variable_decl_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_variable_decl/ast_statement_variable_decl_direct_destroy/ast_statement_variable_decl_direct_destroy.h>
#include <stage/ast/asts/ast_statement/ast_statement_variable_decl/ast_statement_variable_decl_direct_json/ast_statement_variable_decl_direct_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_variable_decl/ast_statement_variable_decl_json/ast_statement_variable_decl_json.h>
#include <stage/ast/asts/ast_statement/ast_statement_variable_decl/ast_statement_variable_decl_log/ast_statement_variable_decl_log.h>
#include <stage/ast/asts/ast_variable_decl/ast_variable_decl_create/ast_variable_decl_create.h>
#include <stage/ast/asts/ast_variable_decl/ast_variable_decl_destroy/ast_variable_decl_destroy.h>
#include <stage/ast/asts/ast_variable_decl/ast_variable_decl_direct_destroy/ast_variable_decl_direct_destroy.h>
#include <stage/ast/asts/ast_variable_decl/ast_variable_decl_direct_json/ast_variable_decl_direct_json.h>
#include <stage/ast/asts/ast_variable_decl/ast_variable_decl_json/ast_variable_decl_json.h>
#include <stage/ast/asts/ast_variable_decl/ast_variable_decl_log/ast_variable_decl_log.h>
#include <stage/ast/type.h>
#include <stage/generator/generator_c/generator_c_block/generator_c_block.h>
#include <stage/generator/generator_c/generator_c_code/generator_c_code.h>
#include <stage/generator/generator_c/generator_c_function_decl/generator_c_function_decl.h>
#include <stage/generator/generator_c/generator_c_node/generator_c_node.h>
#include <stage/generator/generator_c/generator_c_program/generator_c_program.h>
#include <stage/generator/generator_c/generator_c_statement/generator_c_statement_print/generator_c_statement_print.h>
#include <stage/generator/generator_c/generator_c_statement/generator_c_statement_ret/generator_c_statement_ret.h>
#include <stage/generator/generator_c/generator_c_type/generator_c_type.h>
#include <stage/generator/generator_c/generator_c_variable_decl/generator_c_variable_decl.h>
#include <stage/generator/generator_create/generator_create.h>
#include <stage/generator/generator_destroy/generator_destroy.h>
#include <stage/generator/type.h>
#include <stage/parser/parser_create/parser_create.h>
#include <stage/parser/parser_destroy/parser_destroy.h>
#include <stage/parser/parser_eat/parser_eat.h>
#include <stage/parser/parser_expect/parser_expect.h>
#include <stage/parser/parser_expect_get/parser_expect_get.h>
#include <stage/parser/parser_has/parser_has.h>
#include <stage/parser/parser_json/parser_json.h>
#include <stage/parser/parser_log/parser_log.h>
#include <stage/parser/parser_next/parser_next.h>
#include <stage/parser/parser_operator_expect/parser_operator_expect.h>
#include <stage/parser/parser_parse/parser_parse_all/parser_parse_all.h>
#include <stage/parser/parser_parse/parser_parse_arguments/parser_parse_arguments.h>
#include <stage/parser/parser_parse/parser_parse_block/parser_parse_block.h>
#include <stage/parser/parser_parse/parser_parse_expression_item/parser_parse_expression_item.h>
#include <stage/parser/parser_parse/parser_parse_expressions/parser_parse_expressions.h>
#include <stage/parser/parser_parse/parser_parse_function_decl/parser_parse_function_decl.h>
#include <stage/parser/parser_parse/parser_parse_node/parser_parse_node.h>
#include <stage/parser/parser_parse/parser_parse_parameters/parser_parse_parameters.h>
#include <stage/parser/parser_parse/parser_parse_statement/parser_parse_statement.h>
#include <stage/parser/parser_parse/parser_parse_statement_print/parser_parse_statement_print.h>
#include <stage/parser/parser_parse/parser_parse_statement_return/parser_parse_statement_return.h>
#include <stage/parser/parser_prev/parser_prev.h>
#include <stage/parser/parser_skip/parser_skip.h>
#include <stage/parser/type.h>
#include <stage/scanner/scanner_create/scanner_create.h>
#include <stage/scanner/scanner_destroy/scanner_destroy.h>
#include <stage/scanner/scanner_error/scanner_error.h>
#include <stage/scanner/scanner_json/scanner_json.h>
#include <stage/scanner/scanner_log/scanner_log.h>
#include <stage/scanner/scanner_scan/scanner_scan.h>
#include <stage/scanner/scanner_scan_comment_inline/scanner_scan_comment_inline.h>
#include <stage/scanner/scanner_scan_comment_multiline/scanner_scan_comment_multiline.h>
#include <stage/scanner/scanner_scan_identifier/scanner_scan_identifier.h>
#include <stage/scanner/scanner_scan_number/scanner_scan_number.h>
#include <stage/scanner/scanner_scan_string/scanner_scan_string.h>
#include <stage/scanner/scanner_set/scanner_set.h>
#include <stage/scanner/type.h>
#include <stage/token/token_char_type/token_char_type.h>
#include <stage/token/token_create/token_create.h>
#include <stage/token/token_free/token_free.h>
#include <stage/token/token_json/token_json.h>
#include <stage/token/token_keyword_type/token_keyword_type.h>
#include <stage/token/token_location_json/token_location_json.h>
#include <stage/token/token_log/token_log.h>
#include <stage/token/token_name/token_name.h>
#include <stage/token/token_operator_keyword_type/token_operator_keyword_type.h>
#include <stage/token/token_operator_name/token_operator_name.h>
#include <stage/token/token_operator_type/token_operator_type.h>
#include <stage/token/token_type/token_type.h>
#include <stage/token/type.h>
#include <stage/value/type.h>
#include <stage/value/value_create/value_create.h>
#include <stage/value/value_destroy/value_destroy.h>
#include <stage/value/value_json/value_json.h>
#include <stage/value/value_log/value_log.h>
#include <stage/value/value_name/value_name.h>
#include <utility/array/array_append/array_append.h>
#include <utility/array/array_create/array_create.h>
#include <utility/array/array_delete/array_delete.h>
#include <utility/array/array_destroy/array_destroy.h>
#include <utility/array/array_get/array_get.h>
#include <utility/array/array_prepend/array_prepend.h>
#include <utility/array/array_resize/array_resize.h>
#include <utility/array/array_size/array_size.h>
#include <utility/array/type.h>
#include <utility/buffer/buffer_append/buffer_append.h>
#include <utility/buffer/buffer_append_char/buffer_append_char.h>
#include <utility/buffer/buffer_append_char_begin/buffer_append_char_begin.h>
#include <utility/buffer/buffer_append_str/buffer_append_str.h>
#include <utility/buffer/buffer_append_str_begin/buffer_append_str_begin.h>
#include <utility/buffer/buffer_append_wchar/buffer_append_wchar.h>
#include <utility/buffer/buffer_compare/buffer_compare.h>
#include <utility/buffer/buffer_create/buffer_create.h>
#include <utility/buffer/buffer_destroy/buffer_destroy.h>
#include <utility/buffer/buffer_destroy_and_get/buffer_destroy_and_get.h>
#include <utility/buffer/buffer_equals/buffer_equals.h>
#include <utility/buffer/buffer_is/buffer_is.h>
#include <utility/buffer/buffer_lower_str/buffer_lower_str.h>
#include <utility/buffer/buffer_print/buffer_print.h>
#include <utility/buffer/buffer_set/buffer_set.h>
#include <utility/buffer/buffer_set_str/buffer_set_str.h>
#include <utility/buffer/buffer_upper_str/buffer_upper_str.h>
#include <utility/buffer/type.h>
#include <utility/convert/convert_double2string/convert_double2string.h>
#include <utility/convert/convert_float2string/convert_float2string.h>
#include <utility/convert/convert_int2string/convert_int2string.h>
#include <utility/convert/convert_size2string/convert_size2string.h>
#include <utility/file/file_append/file_append.h>
#include <utility/file/file_create/file_create.h>
#include <utility/file/file_delete/file_delete.h>
#include <utility/file/file_exists/file_exists.h>
#include <utility/file/file_reads/file_reads.h>
#include <utility/file/file_size/file_size.h>
#include <utility/file/file_write/file_write.h>
#include <utility/hashmap/hashmap_create/hashmap_create.h>
#include <utility/hashmap/hashmap_destroy/hashmap_destroy.h>
#include <utility/hashmap/hashmap_put/hashmap_put.h>
#include <utility/hashmap/hashmap_remove/hashmap_remove.h>
#include <utility/hashmap/hashmap_size/hashmap_size.h>
#include <utility/hashmap/type.h>
#include <utility/io/io_directory/io_directory.h>
#include <utility/log/log_error/log_error.h>
#include <utility/log/log_fatal/log_fatal.h>
#include <utility/log/log_info/log_info.h>
#include <utility/memory/memory_allocation/memory_allocation.h>
#include <utility/memory/memory_allocation_soft/memory_allocation_soft.h>
#include <utility/memory/memory_calloc/memory_calloc.h>
#include <utility/memory/memory_copy/memory_copy.h>
#include <utility/memory/memory_destroy/memory_destroy.h>
#include <utility/memory/memory_move/memory_move.h>
#include <utility/memory/memory_realloc/memory_realloc.h>
#include <utility/memory/memory_set/memory_set.h>
#include <utility/string/string_arabic2persian/string_arabic2persian.h>
#include <utility/string/string_char_is_alnum/string_char_is_alnum.h>
#include <utility/string/string_char_is_alpha/string_char_is_alpha.h>
#include <utility/string/string_char_is_digit/string_char_is_digit.h>
#include <utility/string/string_compare/string_compare.h>
#include <utility/string/string_convert_utf8_to_english_digit/string_convert_utf8_to_english_digit.h>
#include <utility/string/string_duplicate/string_duplicate.h>
#include <utility/string/string_ends/string_ends.h>
#include <utility/string/string_escaping/string_escaping.h>
#include <utility/string/string_hash/string_hash.h>
#include <utility/string/string_length/string_length.h>
#include <utility/string/string_replace_all/string_replace_all.h>
#include <utility/string/string_replace_all_substrings/string_replace_all_substrings.h>
#include <utility/string/string_starts/string_starts.h>
#include <utility/utf8/utf8_char_decode/utf8_char_decode.h>
#include <utility/utf8/utf8_char_length/utf8_char_length.h>
#include <utility/utf8/utf8_decode/utf8_decode.h>
#include <utility/utf8/utf8_is_alpha/utf8_is_alpha.h>
#include <utility/utf8/utf8_is_continuation_byte/utf8_is_continuation_byte.h>
#include <utility/utf8/utf8_is_digit/utf8_is_digit.h>
#include <utility/utf8/utf8_is_valid/utf8_is_valid.h>
#include <utility/utf8/utf8_strlen/utf8_strlen.h>

#endif // _BASE_ALL_H_
