export enum LexerMessageKeys {
    LEXER_PREFIX = 'LEXER_PREFIX',
    LEXER_INVALID_UNEXPECTED_CHAR = 'LEXER_INVALID_UNEXPECTED_CHAR',
    LEXER_UNTERMINATED_MULTI_LINE_COMMENT_BLOCK = 'LEXER_UNTERMINATED_MULTI_LINE_COMMENT_BLOCK',
    LEXER_UNCLOSED_STRING_LITERAL = 'LEXER_UNCLOSED_STRING_LITERAL',
};
