#ifndef _SRC_STAGE_GENERATOR_GENERATOR_DESTROY_GENERATOR_DESTROY_H_
#define _SRC_STAGE_GENERATOR_GENERATOR_DESTROY_GENERATOR_DESTROY_H_

// base
#include <base.h>

void generator_destroy(generator_t* generator);

#endif // _SRC_STAGE_GENERATOR_GENERATOR_DESTROY_GENERATOR_DESTROY_H_
