# .github/workflows/label-size.yml
name: Apply size label

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files count
        id: files
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) core.setFailed('No pull_request in context');
            let page = 1;
            let fileCount = 0;
            while (true) {
              const res = await github.rest.pulls.listFiles({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                per_page: 100,
                page
              });
              if (!res || !res.data) break;
              fileCount += res.data.length;
              if (res.data.length < 100) break;
              page++;
            }
            core.setOutput("count", fileCount);

      - name: Determine size label
        id: size
        run: |
          count=${{ steps.files.outputs.count }}
          if [ -z "$count" ]; then echo "label=size/XS" >> $GITHUB_OUTPUT; exit 0; fi
          if [ "$count" -le 5 ]; then echo "label=size/XS" >> $GITHUB_OUTPUT
          elif [ "$count" -le 15 ]; then echo "label=size/S" >> $GITHUB_OUTPUT
          elif [ "$count" -le 50 ]; then echo "label=size/M" >> $GITHUB_OUTPUT
          elif [ "$count" -le 100 ]; then echo "label=size/L" >> $GITHUB_OUTPUT
          else echo "label=size/XL" >> $GITHUB_OUTPUT
          fi

      - name: Apply size label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.size.outputs.label }}
