name: 🔧 Basic checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  test-git-clone:
    timeout-minutes: 10
    name: 'Test git clone on ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-24.04}
          - {os: ubuntu-22.04}
          - {os: macos-15}
          - {os: macos-14}
          - {os: macos-13}
          - {os: windows-2025}
          - {os: windows-2022}
    steps:
      - name: 'Checkout ${{ github.ref }} ( ${{ github.sha }} )'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
