#ifndef _SRC_UTILITY_CONVERT_CONVERT_FLOAT2STRING_CONVERT_FLOAT2STRING_H_
#define _SRC_UTILITY_CONVERT_CONVERT_FLOAT2STRING_CONVERT_FLOAT2STRING_H_

#include <stdio.h>  // for snprintf

// base
#include <base.h>

char* convert_float2string(float value);

#endif // _SRC_UTILITY_CONVERT_CONVERT_FLOAT2STRING_CONVERT_FLOAT2STRING_H_
